use std::{
    path::{Path, PathBuf},
    sync::Arc,
};

use config_file2::LoadConfigFile;
use log::{debug, info, warn};
use parking_lot::Mutex;
use path_absolutize::Absolutize;
use rayon::prelude::*;
use zeroize::Zeroizing;

use crate::{
    config::{CONFIG_FILE_NAME, Config},
    error::{Error, Result},
    utils::{
        CryptPolicy, Progress, git_z_path, is_file_encrypted, prompt_password,
        resolve_target_files, style::Colorize,
    },
};

pub const GIT_CONFIG_PREFIX: &str =
    const_str::replace!(concat!(env!("CARGO_CRATE_NAME"), "."), "_", "-");

/// The pre-commit hook content that runs `git-se check --staged` before every
/// commit, so only files part of the current commit are checked.
const PRE_COMMIT_HOOK: &[u8] = br#"#!/bin/sh
# Auto-generated by git-se install
git-se check --staged
if [ $? -ne 0 ]; then
    echo "Please run 'git-se e' to encrypt them before committing."
    exit 1
fi
"#;

#[derive(Debug, Clone, Default)]
pub struct Repo {
    /// The absolute path of the opened repo.
    pub path: PathBuf,
    /// The resolved per-worktree git dir (`git rev-parse --absolute-git-dir`,
    /// canonicalized).
    ///
    /// Equals `<path>/.git` for a normal repository, but differs for linked
    /// worktrees (`<main>/.git/worktrees/<name>`) and submodules
    /// (`<superproject>/.git/modules/<name>`). Falls back to `<path>/.git`
    /// when the directory is not a git repository. (`git` itself is always
    /// required: [`Repo::open`] fails with [`Error::GitUnavailable`] when no
    /// working git binary exists.)
    pub git_dir: PathBuf,
    /// The resolved common git dir (`git rev-parse --git-common-dir`,
    /// canonicalized), where hooks and shared config live. Equals
    /// [`Repo::git_dir`] unless this is a linked worktree.
    pub git_common_dir: PathBuf,
    /// Directories no operation may ever touch: the resolved git dirs above.
    /// Tracked separately because a `--separate-git-dir` layout can place
    /// them inside the worktree under an arbitrary name, where the lexical
    /// `.git` check cannot see them (2026-07 audit).
    pub(crate) protected_dirs: crate::utils::ProtectedDirs,
    pub conf: Config,
    /// The held repository lock — `None` only for a plain directory without
    /// a git dir. Shared across clones; released when the last `Repo` (or
    /// handle) drops.
    pub lock: Option<Arc<crate::crypt::RepoLock>>,
}

impl Repo {
    /// Open a repo. The `path` argument must be an absolute path.
    pub fn open(path: impl AsRef<Path>) -> Result<Self> {
        if !path.as_ref().is_absolute() {
            return Err(Error::RepoPathNotAbsolute(path.as_ref().to_path_buf()));
        }
        let mut repo_path = path.as_ref().to_path_buf();
        if !repo_path.exists() {
            return Err(Error::RepoNotFound(repo_path));
        }
        if !repo_path.is_dir() {
            return Err(Error::NotADirectory(repo_path));
        }
        // Convenience: `git-se -r <repo>/.git` means `<repo>`. Compared
        // case-insensitively so `.GIT` (a case-insensitive filesystem, or a
        // hand-made alias symlink) resolves the same way (H-02).
        if repo_path
            .file_name()
            .is_some_and(|name| name.eq_ignore_ascii_case(".git"))
        {
            repo_path.pop();
        }

        // A working git binary is a hard requirement. Every boundary git-se
        // enforces — worktree top level, git dir, common dir, "inside a git
        // dir" — is answered by git plumbing, and when git was missing those
        // lookups silently fell back to path-shape guesses: a
        // `--separate-git-dir` layout (no `.git` anywhere in its path)
        // slipped past all of them and its refs got encrypted under
        // `--allow-password-change` (H-08).
        ensure_git_available()?;

        reject_paths_inside_git_dir(&mut repo_path)?;

        info!("Open repo: {}", repo_path.display());
        let (git_dir, git_common_dir) = resolve_git_dirs(&repo_path);

        // Independent second guard, in case a fallback git dir was assumed
        // (not a repository). `dunce` throughout: the git dirs are
        // canonicalized the same way, and a mismatch in path flavor would
        // make this comparison silently false.
        let canonical = dunce::canonicalize(&repo_path).unwrap_or_else(|_| repo_path.clone());
        if canonical.starts_with(&git_dir) || canonical.starts_with(&git_common_dir) {
            return Err(Error::PathInsideGitDir(canonical));
        }
        let mut protected_dirs = crate::utils::ProtectedDirs::new(
            vec![git_dir.clone(), git_common_dir.clone()],
            &canonical,
        );
        // Nested-repository protection (2026-07 audit): discover every
        // nested git dir — verified `.git` pointer targets, nested `.git`
        // directories, bare repos — BEFORE anything walks, matches, or
        // sweeps the tree, then confirm the finds. Fail-closed throughout:
        // an unreadable `.git` pointer, a traversal error, or a candidate
        // that cannot be confirmed aborts the open.
        let nested = crate::utils::discover_nested_git_dirs(&repo_path, &protected_dirs)?;
        confirm_nested_git_dirs(nested, &repo_path, &canonical, &mut protected_dirs)?;

        let config_file_path = repo_path.join(CONFIG_FILE_NAME);
        validate_config_file(&config_file_path, &canonical)?;
        let conf = Config::load_or_default(&config_file_path)
            .map_err(|e| Error::Config(e.to_string()))?
            .with_repo_path(&repo_path);
        // Hold the repo lock before touching recovery or the sweep: without
        // it, a second process would mistake this one's running transaction
        // for a crashed one — "recovering" its backups mid-commit and
        // deleting its temp files. The handle lives on the `Repo`, so the
        // lock is released when the last `Repo` drops rather than tying up
        // the repository until process exit.
        let lock = crate::crypt::acquire_repo_lock(&git_dir)?;
        let repo = Self {
            path: repo_path,
            git_dir,
            git_common_dir,
            protected_dirs,
            conf,
            lock,
        };
        // An interrupted commit phase is undone before anything else runs, so
        // no command ever starts from a half-replaced repository. When
        // recovery cannot complete, opening FAILS: running `check`, `add` or
        // anything else on a partially recovered tree would proceed from a
        // mixed state (an interrupted password change leaves old- and
        // new-password ciphertext side by side, and the passwordless staged
        // check only sees formats). The user restores the listed backups
        // manually, then removes the journal.
        // The unified protected set is handed to recovery too: a journal
        // (legacy, damaged, or hostile) naming a path inside ANY protected
        // git dir — including a nested one discovered above — is rejected
        // as corrupt, never acted on.
        let recovery = crate::crypt::recover_interrupted_commit(
            repo.git_dir(),
            repo.path(),
            &repo.protected_dirs,
        );
        if recovery.journal_corrupt {
            return Err(Error::JournalCorrupt(crate::crypt::journal_path(
                repo.git_dir(),
            )));
        }
        if let Some(reason) = recovery.journal_unreadable {
            return Err(Error::JournalUnreadable(
                crate::crypt::journal_path(repo.git_dir()),
                reason,
            ));
        }
        if !recovery.failed.is_empty() {
            return Err(Error::RecoveryIncomplete(
                recovery.failed.len(),
                crate::crypt::journal_path(repo.git_dir()),
            ));
        }
        if recovery.journal_leftover {
            return Err(Error::JournalLeftover(crate::crypt::journal_path(
                repo.git_dir(),
            )));
        }
        crate::utils::exclude_temp_files(&repo.git_common_dir);
        // While a journal survives recovery, its backups are the user's last
        // recovery material — sweep temp files only, never those backups.
        crate::utils::sweep_stale_temp_files(
            repo.path(),
            recovery.failed.is_empty(),
            &repo.protected_dirs,
        );
        // Scrub passwords stored by older versions. Skipped in unit tests so
        // that running the test suite cannot touch a real repo's config.
        #[cfg(not(test))]
        repo.scrub_legacy_key();
        Ok(repo)
    }

    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// The directories no operation may touch (the resolved git dirs).
    /// Returned by value so callers can borrow `self.conf` mutably alongside.
    #[must_use]
    pub fn protected(&self) -> crate::utils::ProtectedDirs {
        self.protected_dirs.clone()
    }

    /// The per-worktree git dir (see [`Repo::git_dir`]).
    #[must_use]
    pub fn git_dir(&self) -> &Path {
        &self.git_dir
    }

    pub fn to_absolute_path(&self, path: impl AsRef<Path>) -> PathBuf {
        self.path.join(path.as_ref())
    }

    /// Change the master password: decrypt every listed file with the old
    /// password, then re-encrypt everything with the new one.
    ///
    /// The old password is taken from `GIT_SE_PASSWORD` when set, otherwise
    /// prompted; it is only asked for when the list actually contains
    /// ciphertext — with none, there is nothing to decrypt and the command
    /// simply establishes the new password on the listed (plaintext) files.
    /// The new password is always prompted (twice, echo disabled). Nothing is
    /// persisted anywhere — the password only lives in memory for the
    /// duration of the operation.
    pub fn change_password_interactive(&self) -> Result<()> {
        let target_files = crate::utils::resolve_target_files(
            &[],
            &self.conf.crypt_list,
            self.path(),
            &self.protected_dirs,
        )?;
        if target_files.is_empty() {
            return Err(Error::NoFile("re-encrypt"));
        }
        // Whether the OLD password must be asked for at all. Strict
        // probe: an unreadable file must not read as "plaintext", or a
        // list whose only ciphertext is unreadable would skip the old
        // password entirely and fail confusingly mid-transaction.
        let mut has_encrypted = false;
        for f in &target_files {
            if crate::utils::is_file_encrypted_strict(f)? {
                has_encrypted = true;
                break;
            }
        }

        // Order matters (H-05): validate the old password IN MEMORY and
        // confirm the new password BEFORE any file is touched, so a mistyped
        // confirmation cannot cost anything.
        let old_key = if has_encrypted {
            let old_key = crate::utils::get_password("Please input your OLD key: ")?;
            crate::crypt::precheck_password(
                &target_files,
                crate::crypt::Password::new(old_key.as_bytes()),
            )?;
            old_key
        } else {
            Zeroizing::new(String::new())
        };

        let new_key = prompt_password("Please input your NEW key: ")?;
        let confirm = prompt_password("Please confirm your NEW key: ")?;
        if new_key.as_str() != confirm.as_str() {
            return Err(Error::PasswordMismatch);
        }

        // One transaction: old ciphertext → new ciphertext per file, all
        // committed together. The plaintext only ever exists in temp files,
        // so a failure at any point leaves every file encrypted with the OLD
        // password rather than stranding the repo in plaintext or in a mix.
        //
        // When nothing was encrypted, the old password is never consulted
        // (`precheck_password` no-ops and plaintext files go straight to the
        // new-password branch), so the new one stands in for it — an empty
        // old password would be rejected as an `EmptyKey`.
        let effective_old = if has_encrypted { &old_key } else { &new_key };
        crate::crypt::change_password(
            self,
            crate::crypt::Password::new(effective_old.as_bytes()),
            crate::crypt::Password::new(new_key.as_bytes()),
        )?;
        info!("Master key changed; all listed files were re-encrypted.");
        Ok(())
    }

    /// One-time migration: versions that stored the password in the repo-local
    /// git config get it scrubbed. Best-effort; only logs on failure.
    pub fn scrub_legacy_key(&self) {
        let legacy_key = format!("{GIT_CONFIG_PREFIX}key");
        if self.get_config("key").is_err() {
            return;
        }
        if self.run(&["config", "--unset", &legacy_key]).is_ok() {
            warn!(
                "Removed the password stored in .git/config by an older git-se version; \
                 passwords are no longer persisted."
            );
        } else {
            warn!(
                "A password from an older git-se version is still stored in .git/config and \
                 could not be removed automatically; please run \
                 `git config --local --unset {legacy_key}`."
            );
        }
    }

    /// Check if all files in the crypt list (or given paths) are encrypted.
    ///
    /// When `staged` is true, only files staged for the current commit are
    /// checked, by intersecting staged files against the crypt list. This is
    /// used by the pre-commit hook to avoid checking the entire repo.
    ///
    /// Returns `Ok(())` if all files are encrypted, or an error summarizing
    /// which files are not encrypted. The process exits with a non-zero code
    /// when files are not encrypted, suitable for CI usage.
    pub fn check(&self, paths: &[PathBuf], staged: bool) -> Result<()> {
        if staged {
            return self.check_staged();
        }
        let target_files = resolve_target_files(
            paths,
            &self.conf.crypt_list,
            self.path(),
            &self.protected_dirs,
        )?;

        if target_files.is_empty() {
            return Err(Error::NoFile("check"));
        }

        println!(
            "\n{} {} {}",
            "Checking encryption status".bold(),
            format!("({} files)", target_files.len()).cyan(),
            ":".dimmed()
        );

        let pb = Progress::new(target_files.len(), "Check");
        let not_encrypted: Mutex<Vec<PathBuf>> = Mutex::new(Vec::new());

        target_files.par_iter().try_for_each(|f| -> Result<()> {
            if !is_file_encrypted(f)? {
                let mut list = not_encrypted.lock();
                let relative = pathdiff::diff_paths(f, &self.path).unwrap_or_else(|| f.clone());
                list.push(relative);
            }
            pb.inc(1);
            Ok(())
        })?;

        pb.finish_and_clear();

        let not_encrypted = not_encrypted.into_inner();
        let total = target_files.len();
        let encrypted_count = total - not_encrypted.len();

        if not_encrypted.is_empty() {
            println!(
                "\n{}: All {} files are encrypted.",
                "Check complete".bold(),
                total.to_string().green(),
            );
            Ok(())
        } else {
            println!(
                "\n{} files are {}:",
                not_encrypted.len().to_string().yellow(),
                "NOT encrypted".yellow()
            );
            for f in &not_encrypted {
                println!("  - {}", f.display());
            }

            println!(
                "\n{}: {}/{} files encrypted",
                "Check complete".bold(),
                encrypted_count.to_string().green(),
                total,
            );

            Err(Error::FilesNotEncrypted(not_encrypted.len(), total))
        }
    }

    /// The policy that governs the tree about to be committed.
    ///
    /// Read from the **index** copy of the config, not the working-tree copy:
    /// otherwise an unstaged edit that empties `crypt_list` would disable the
    /// check for a commit whose own config still demands encryption (H-01).
    ///
    /// A staged config that does not parse is a **hard error**. Falling back
    /// to the working-tree list, as this used to, let a corrupt staged config
    /// wave plaintext through: the policy actually being committed was simply
    /// never consulted.
    ///
    /// The working-tree list is unioned in. `crypt_list` is an allowlist, so a
    /// union can only ever demand more encryption — the fail-closed direction
    /// — and it keeps the check working before the config is ever staged.
    fn staged_policy(&self, config_staged: bool) -> Result<CryptPolicy> {
        let mut list = self.conf.crypt_list.clone();
        if config_staged {
            let bytes =
                self.run_with_output_bytes(&["cat-file", "blob", &format!(":{CONFIG_FILE_NAME}")])?;
            let text = String::from_utf8(bytes).map_err(|e| {
                Error::Config(format!("the staged {CONFIG_FILE_NAME} is not UTF-8: {e}"))
            })?;
            let staged = Config::parse_crypt_list(&text).map_err(|e| {
                Error::Config(format!(
                    "the staged {CONFIG_FILE_NAME} does not parse ({e}); refusing to check the \
                     commit against a different policy than the one it contains"
                ))
            })?;
            list.extend(staged);
        } else {
            debug!("{CONFIG_FILE_NAME} is not in the index; using the working-tree crypt list");
        }
        // An entry the policy cannot interpret (e.g. `d/../x`) is a hard
        // error here — fail-closed, never a silently weaker check.
        CryptPolicy::try_new(&list, &self.protected_dirs)
    }

    /// Staged-mode check (used by the pre-commit hook).
    ///
    /// Everything comes from one **index** snapshot — the policy, the file
    /// list, and the blobs — i.e. exactly the tree a commit would contain.
    ///
    /// The whole index is enumerated, not just what differs from `HEAD`.
    /// A config change that *widens* the crypt list brings previously
    /// unencrypted files into scope without touching them, and a diff-based
    /// check cannot see those at all (H-01).
    fn check_staged(&self) -> Result<()> {
        // `--stage -z`: every index entry with its mode and merge stage,
        // filenames verbatim (no C-style quoting, so non-ASCII names are not
        // mangled and silently skipped).
        let raw = self.run_with_output_bytes(&["ls-files", "--stage", "-z"])?;
        let entries = parse_ls_files_stage(&raw);

        let config_staged = entries
            .iter()
            .any(|e| e.path.path == Path::new(CONFIG_FILE_NAME));
        let policy = self.staged_policy(config_staged)?;
        if policy.is_empty() {
            println!("No staged files need encryption check.");
            return Ok(());
        }

        let mut staged: Vec<IndexPath> = Vec::new();
        let mut unmerged: Vec<PathBuf> = Vec::new();
        for entry in entries {
            if !policy.matches(&entry.path.path) {
                continue;
            }
            match entry.kind {
                // An unmerged path has no stage-0 blob to read, so its content
                // is unverifiable. Fail closed.
                StagedKind::Unmerged => unmerged.push(entry.path.path),
                StagedKind::Regular => staged.push(entry.path),
                // Symlink blobs hold a target path and gitlinks hold a commit
                // id; neither is a file this tool encrypts.
                StagedKind::Other => {}
            }
        }
        unmerged.sort_unstable();
        unmerged.dedup(); // an unmerged path is listed once per stage

        if staged.is_empty() && unmerged.is_empty() {
            println!("No staged files need encryption check.");
            return Ok(());
        }

        let total = staged.len() + unmerged.len();
        println!(
            "\n{} {} {}",
            "Checking staged content".bold(),
            format!("({total} files)").cyan(),
            ":".dimmed()
        );

        let pb = Progress::new(staged.len(), "Check");
        let blobs = self.read_blob_prefixes(":", &staged, crate::crypt::MIN_ENCRYPTED_LEN)?;
        pb.inc(staged.len() as u64);
        pb.finish_and_clear();

        // Unmerged paths start out in the failure list: their content cannot
        // be read, and "unverifiable" must not read as "fine".
        let mut not_encrypted = unmerged;
        for (entry, blob) in staged.iter().zip(blobs) {
            if !blob.is_some_and(|b| b.is_encrypted()) {
                not_encrypted.push(entry.path.clone());
            }
        }

        not_encrypted.sort_unstable();
        let encrypted_count = total - not_encrypted.len();

        if not_encrypted.is_empty() {
            println!(
                "\n{}: All {} staged files are encrypted.",
                "Check complete".bold(),
                total.to_string().green(),
            );
            Ok(())
        } else {
            println!(
                "\n{} staged files are {} (in the index):",
                not_encrypted.len().to_string().yellow(),
                "NOT encrypted".yellow()
            );
            for f in &not_encrypted {
                println!("  - {}", f.display());
            }
            println!(
                "\n{}: {}/{} staged files encrypted",
                "Check complete".bold(),
                encrypted_count.to_string().green(),
                total,
            );
            Err(Error::FilesNotEncrypted(not_encrypted.len(), total))
        }
    }

    /// The directory git actually runs hooks from.
    ///
    /// Asks git rather than assuming `<git-common-dir>/hooks`: `core.hooksPath`
    /// redirects hooks elsewhere, and installing into the default anyway
    /// produced a hook git would never run — while reporting success.
    ///
    /// Falls back to the common dir when git cannot be consulted; that is the
    /// historical location and works for every repository without
    /// `core.hooksPath`.
    fn hooks_dir(&self) -> PathBuf {
        let Ok(out) = self.run_with_output(&["rev-parse", "--git-path", "hooks"]) else {
            return self.git_common_dir.join("hooks");
        };
        let trimmed = out.trim();
        if trimmed.is_empty() {
            return self.git_common_dir.join("hooks");
        }
        // `--git-path` may answer relative to the working directory.
        Path::new(trimmed).absolutize_from(&self.path).into_owned()
    }

    /// Install a pre-commit hook that runs `git-se check` before each commit.
    ///
    /// Writes `pre-commit` into the directory git itself resolves hooks from
    /// (`git rev-parse --git-path hooks`), so a `core.hooksPath` override is
    /// honored. Without that override it is the *common* git dir, so the hook
    /// also fires for linked worktrees. Fails if a hook already exists and is
    /// not managed by git-se.
    pub fn install_hook(&self) -> Result<()> {
        let hooks_dir = self.hooks_dir();
        std::fs::create_dir_all(&hooks_dir)?;

        let hook_path = hooks_dir.join("pre-commit");

        // `symlink_metadata`, not `exists`: `exists()` follows links, so a
        // DANGLING symlink reads as absent while the write below would follow
        // it and create the target — possibly outside the repository.
        if hook_path.symlink_metadata().is_ok() {
            return Err(Error::HookExists(hook_path));
        }

        // `create_new` (O_CREAT|O_EXCL): the open itself refuses any existing
        // final component — including a symlink, dangling or not — so the
        // content can never land anywhere but at a freshly created hook file.
        let mut file = match std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&hook_path)
        {
            Ok(file) => file,
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
                return Err(Error::HookExists(hook_path));
            }
            Err(e) => return Err(e.into()),
        };
        let written = std::io::Write::write_all(&mut file, PRE_COMMIT_HOOK);

        // Set executable permission on unix. Windows users need Git for Windows
        // (msys-based) which executes the sh hook regardless of the executable
        // bit; a normal `write` is sufficient there.
        #[cfg(unix)]
        let written = written.and_then(|()| {
            use std::os::unix::fs::PermissionsExt;
            file.set_permissions(std::fs::Permissions::from_mode(0o755))
        });

        // A half-written hook must not survive: without it the next install
        // reports HookExists for a file that does not work.
        if let Err(e) = written {
            drop(file);
            let _ = std::fs::remove_file(&hook_path);
            return Err(e.into());
        }

        println!(
            "{} pre-commit hook at {}",
            "Installed".green().bold(),
            hook_path.display()
        );
        Ok(())
    }

    /// Build a `git` command scoped to this repo.
    ///
    /// The master password is scrubbed from the inherited environment so that
    /// git itself, config helpers, and hooks can never see it.
    ///
    /// Repository selection is pinned to the dirs resolved in [`Repo::open`]:
    /// the ambient [`GIT_REPO_ENV_VARS`] are dropped and `--git-dir` /
    /// `--work-tree` are passed explicitly (command-line beats environment).
    /// Without this, `GIT_DIR=<other-repo>` silently redirected every call.
    fn git_command(&self) -> std::process::Command {
        let mut cmd = std::process::Command::new("git");
        cmd.current_dir(&self.path)
            .env_remove(crate::utils::PASSWORD_ENV_VAR);
        for var in GIT_REPO_ENV_VARS {
            cmd.env_remove(var);
        }

        // `GIT_INDEX_FILE` needs judgement rather than a blanket removal:
        // `git commit --only <paths>` builds a temporary index inside the git
        // dir and points the hook at it, so dropping it would make the
        // pre-commit check inspect the wrong index. Keep it only when it
        // really does live inside our git dir; anything else is a redirect.
        if let Some(index) = std::env::var_os("GIT_INDEX_FILE") {
            let inside = dunce::canonicalize(PathBuf::from(&index).absolutize_from(&self.path))
                .is_ok_and(|c| c.starts_with(&self.git_dir) || c.starts_with(&self.git_common_dir));
            if !inside {
                warn!("Ignoring GIT_INDEX_FILE: it points outside this repository's git dir");
                cmd.env_remove("GIT_INDEX_FILE");
            }
        }

        // Bind explicitly only when the paths are in a form git can parse.
        // `dunce::canonicalize` normally strips the Windows extended-length
        // prefix, but it cannot for paths that genuinely require it (longer
        // than MAX_PATH, reserved names), and git rejects `\\?\...` outright.
        // Falling back to cwd-based discovery keeps those repos working: the
        // env scrubbing above is what actually closes the redirect hole, and
        // `current_dir` is already the verified top level — this binding is
        // defence in depth on top of that.
        if is_verbatim(&self.git_dir) || is_verbatim(&self.path) {
            debug!("extended-length paths: leaving repo discovery to the working directory");
        } else {
            cmd.arg("--git-dir")
                .arg(&self.git_dir)
                .arg("--work-tree")
                .arg(&self.path);
        }

        // Replacement objects would let anything that can write a ref (or set
        // GIT_REPLACE_REF_BASE) substitute the commit the password check
        // authenticates against, so a wrong password verifies against an
        // attacker-chosen tree. git-se never has a legitimate use for them.
        cmd.arg("--no-replace-objects");
        // Crypt-list entries reach git as `:<path>` object names; pathspec
        // magic like `:(glob)` must never be interpreted.
        cmd.arg("--literal-pathspecs");

        // Force English output in tests so we can match on stderr reliably.
        if cfg!(test) {
            cmd.env("LC_ALL", "C.UTF-8").env("LANGUAGE", "C.UTF-8");
        }
        cmd
    }

    /// Run a `git` command in the repo, discarding its stdout/stderr.
    pub fn run<S: AsRef<std::ffi::OsStr>>(&self, args: &[S]) -> Result<()> {
        let output = self.git_command().args(args).output()?;
        if !output.status.success() {
            return Err(Error::Git(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }
        Ok(())
    }

    /// Run a `git` command and return its stdout as a `String`.
    pub fn run_with_output<S: AsRef<std::ffi::OsStr>>(&self, args: &[S]) -> Result<String> {
        String::from_utf8(self.run_with_output_bytes(args)?)
            .map_err(|e| Error::Other(format!("git output not UTF-8: {e}")))
    }

    /// Run a `git` command and return its raw stdout bytes.
    ///
    /// Needed for `-z` output, which is NUL-separated and may contain
    /// non-UTF-8 filenames.
    pub fn run_with_output_bytes<S: AsRef<std::ffi::OsStr>>(&self, args: &[S]) -> Result<Vec<u8>> {
        let output = self.git_command().args(args).output()?;
        if !output.status.success() {
            return Err(Error::Git(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }
        Ok(output.stdout)
    }

    /// Run a `git` command, capturing at most `cap` bytes of stdout.
    ///
    /// The child is killed once `cap` bytes have been read, so this stays
    /// cheap even for huge blobs (e.g. `git show HEAD:large.bin` during the
    /// password pre-check). Because of the early kill, the exit status is
    /// meaningless and therefore ignored: callers must treat an empty result
    /// as "no usable output".
    pub(crate) fn run_with_output_bytes_capped<S: AsRef<std::ffi::OsStr>>(
        &self,
        args: &[S],
        cap: usize,
    ) -> Result<Vec<u8>> {
        use std::io::Read as _;
        let mut child = self
            .git_command()
            .args(args)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::null())
            .spawn()?;
        let mut buf = Vec::new();
        if let Some(stdout) = child.stdout.take() {
            stdout.take(cap as u64).read_to_end(&mut buf)?;
        }
        let _ = child.kill(); // no-op when git already exited (blob smaller than cap)
        let _ = child.wait();
        Ok(buf)
    }

    /// Run one `git cat-file` batch request over `specs`, handing each output
    /// record to `handle` in order.
    ///
    /// The request list is written from its own thread: pushing it all up
    /// front would deadlock as soon as git's output filled the pipe.
    fn cat_file_batch(
        &self,
        mode: &str,
        specs: Vec<Vec<u8>>,
        mut handle: impl FnMut(&mut dyn std::io::BufRead) -> Result<()>,
    ) -> Result<()> {
        use std::io::{BufReader, Write};

        let count = specs.len();
        let mut child = self
            .git_command()
            .args(["cat-file", mode])
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::null())
            .spawn()?;

        let mut stdin = child.stdin.take().expect("stdin piped");
        let writer = std::thread::spawn(move || {
            for spec in specs {
                if stdin.write_all(&spec).is_err() {
                    break;
                }
            }
            // Dropping stdin closes it, ending git's read loop.
        });

        let mut reader = BufReader::new(child.stdout.take().expect("stdout piped"));
        let mut result = Ok(());
        for _ in 0..count {
            if let Err(e) = handle(&mut reader) {
                result = Err(e);
                break;
            }
        }

        let _ = writer.join();
        let _ = child.wait();
        result
    }

    /// Read the leading `cap` bytes of many blobs named `<prefix><path>`.
    ///
    /// The staged check inspects the whole index rather than just the diff, so
    /// one `git show` per candidate is what would hurt: at a few milliseconds
    /// per process, a repository listing thousands of files turns a
    /// pre-commit hook into a coffee break.
    ///
    /// Sizes come from a single `--batch-check` pass, which then decides how
    /// each blob is read:
    ///
    /// - shorter than a valid encrypted file → no read at all;
    /// - small → one shared `--batch` process, so N spawns become one;
    /// - large → an individual capped read, because `--batch` would stream the
    ///   entire blob through the pipe just to look at its first 104 bytes.
    ///
    /// Returns one entry per input, `None` where the blob is missing or too
    /// short to be encrypted.
    pub(crate) fn read_blob_prefixes(
        &self,
        prefix: &str,
        paths: &[IndexPath],
        cap: usize,
    ) -> Result<Vec<Option<BlobPrefix>>> {
        /// Above this size an individual capped read beats streaming the whole
        /// blob through the batch pipe.
        const SMALL_BLOB_LIMIT: u64 = 64 * 1024;

        let spec_for = |p: &IndexPath| {
            let mut spec = Vec::with_capacity(prefix.len() + p.raw.len() + 2);
            spec.extend_from_slice(prefix.as_bytes());
            spec.extend_from_slice(&p.raw);
            spec.push(b'\n');
            spec
        };

        let mut out: Vec<Option<BlobPrefix>> = vec![None; paths.len()];
        // A newline cannot be expressed in the line-oriented batch protocol.
        let (batchable, awkward): (Vec<usize>, Vec<usize>) =
            (0..paths.len()).partition(|&i| !paths[i].raw.contains(&b'\n'));

        for i in awkward {
            out[i] = self.read_one_blob_prefix(prefix, &paths[i], cap, None)?;
        }
        if batchable.is_empty() {
            return Ok(out);
        }

        // Pass 1: sizes only, no content. Every size is stored against its
        // path index: zipping the FILTERED `small` list with the UNFILTERED
        // size list used to hand a blob the previous blob's size whenever a
        // large one sorted before it, which broke the framing check and let
        // a HEAD password anchor hide behind a large plaintext blob.
        let mut sizes_by_index: Vec<Option<u64>> = vec![None; paths.len()];
        {
            let mut sizes: Vec<Option<u64>> = Vec::with_capacity(batchable.len());
            self.cat_file_batch(
                "--batch-check",
                batchable.iter().map(|&i| spec_for(&paths[i])).collect(),
                |reader| {
                    sizes.push(read_batch_check_record(reader)?);
                    Ok(())
                },
            )?;
            for (&i, size) in batchable.iter().zip(&sizes) {
                sizes_by_index[i] = *size;
            }
        }

        let mut small = Vec::new();
        let mut large = Vec::new();
        for &i in &batchable {
            match sizes_by_index[i] {
                // Too short to hold a header plus one chunk.
                Some(n) if n < cap as u64 && n < crate::crypt::MIN_ENCRYPTED_LEN as u64 => {}
                Some(n) if n <= SMALL_BLOB_LIMIT => small.push(i),
                Some(_) => large.push(i),
                None => {}
            }
        }

        // Pass 2a: everything small, in one process.
        if !small.is_empty() {
            let mut results = Vec::with_capacity(small.len());
            self.cat_file_batch(
                "--batch",
                small.iter().map(|&i| spec_for(&paths[i])).collect(),
                |reader| {
                    results.push(read_batch_record(reader, cap)?);
                    Ok(())
                },
            )?;
            for (&i, blob) in small.iter().zip(results) {
                out[i] = blob.map(|prefix| BlobPrefix {
                    prefix,
                    total_len: sizes_by_index[i].unwrap_or(0),
                });
            }
        }

        // Pass 2b: the few large ones, capped so nothing big is transferred.
        for i in large {
            out[i] = self.read_one_blob_prefix(prefix, &paths[i], cap, sizes_by_index[i])?;
        }
        Ok(out)
    }

    /// Capped read of a single blob, killing git once `cap` bytes have arrived.
    ///
    /// `known_size` avoids a redundant `cat-file -s` round trip when the
    /// batch-check pass already reported the size (`None` for paths that
    /// could not go through the batch protocol).
    fn read_one_blob_prefix(
        &self,
        prefix: &str,
        path: &IndexPath,
        cap: usize,
        known_size: Option<u64>,
    ) -> Result<Option<BlobPrefix>> {
        let mut spec = std::ffi::OsString::from(prefix);
        spec.push(path.path.as_os_str());
        let prefix_bytes = self
            .run_with_output_bytes_capped(&[std::ffi::OsStr::new("show"), spec.as_os_str()], cap)?;
        if prefix_bytes.is_empty() {
            return Ok(None);
        }
        let total_len = known_size
            .or_else(|| {
                let mut size_spec = std::ffi::OsString::from(prefix);
                size_spec.push(path.path.as_os_str());
                self.run_with_output(&[
                    std::ffi::OsStr::new("cat-file"),
                    std::ffi::OsStr::new("-s"),
                    size_spec.as_os_str(),
                ])
                .ok()
                .and_then(|s| s.trim().parse().ok())
            })
            .unwrap_or(0);
        Ok(Some(BlobPrefix {
            prefix: prefix_bytes,
            total_len,
        }))
    }

    /// Write a value to `<prefix>.<key>` in the repo-local git config.
    ///
    /// Note: while the value is stored verbatim, [`Repo::get_config`]
    /// currently **trims leading/trailing whitespace on read**, so stored
    /// values (in particular the password) effectively cannot contain
    /// surrounding whitespace. The interactive prompt trims its input for
    /// the same reason.
    pub fn set_config(&self, key: &str, value: &str) -> Result<()> {
        let temp = String::from(GIT_CONFIG_PREFIX) + key;
        self.run(&["config", "--local", &temp, value])
    }

    /// Read `<prefix>.<key>` from the repo-local git config.
    ///
    /// Wrapped in [`Zeroizing`]: the one remaining caller reads the password
    /// left behind by older versions ([`Repo::scrub_legacy_key`]), so the
    /// value must not linger in memory after the read.
    pub fn get_config(&self, key: &str) -> Result<Zeroizing<String>> {
        let temp = String::from(GIT_CONFIG_PREFIX) + key;
        let raw = Zeroizing::new(self.run_with_output(&["config", "--get", &temp])?);
        Ok(Zeroizing::new(raw.trim().to_string()))
    }
}

/// What kind of index entry a staged path refers to.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum StagedKind {
    /// A regular file blob (mode 100644 / 100755) — the only thing git-se
    /// encrypts, and therefore the only thing it can check.
    Regular,
    /// An unmerged path (conflict). Its content lives at stages 1/2/3, so
    /// `git show :<path>` cannot read it.
    Unmerged,
    /// A symlink (120000) or gitlink/submodule (160000).
    Other,
}

/// One entry of `git ls-files --stage -z` output.
#[derive(Debug)]
struct StagedEntry {
    kind: StagedKind,
    path: IndexPath,
}

/// Parse `git ls-files --stage -z` output.
///
/// Each record is `<mode> SP <oid> SP <stage> TAB <path>` followed by NUL.
/// The metadata never contains a tab, so splitting on the first one is exact
/// even for a filename that contains tabs.
fn parse_ls_files_stage(raw: &[u8]) -> Vec<StagedEntry> {
    let mut out = Vec::new();
    for record in raw.split(|&b| b == 0).filter(|s| !s.is_empty()) {
        let Some(tab) = record.iter().position(|&b| b == b'\t') else {
            continue;
        };
        let (meta, path) = record.split_at(tab);
        let path = &path[1..]; // drop the tab
        let meta = String::from_utf8_lossy(meta);
        let mut fields = meta.split(' ');
        let mode = fields.next().unwrap_or_default();
        let _oid = fields.next();
        let stage = fields.next().unwrap_or("0");

        let kind = if stage != "0" {
            StagedKind::Unmerged
        } else if matches!(mode, "100644" | "100755") {
            StagedKind::Regular
        } else {
            StagedKind::Other
        };

        out.push(StagedEntry {
            kind,
            path: IndexPath {
                raw: path.to_vec(),
                path: git_z_path(path),
            },
        });
    }
    out
}

/// The leading bytes of a blob, together with its full length so the chunk
/// framing can be validated without reading the whole thing.
#[derive(Debug, Clone)]
pub(crate) struct BlobPrefix {
    prefix: Vec<u8>,
    pub(crate) total_len: u64,
}

impl BlobPrefix {
    /// Whether this blob is a well-formed encrypted file, as far as a
    /// password-free format check can tell.
    pub(crate) fn is_encrypted(&self) -> bool {
        crate::crypt::is_encrypted_header(&self.prefix)
            && crate::crypt::framing_is_plausible(self.total_len)
    }
}

/// One entry of the git index (or of a tree listing, for HEAD anchors).
#[derive(Debug, Clone)]
pub(crate) struct IndexPath {
    /// Exactly the bytes git printed, used to address the blob again.
    pub(crate) raw: Vec<u8>,
    /// The same path as a `Path`, for policy matching and display.
    pub(crate) path: PathBuf,
}

/// Read one `git cat-file --batch-check` record: `<oid> SP <type> SP <size>`,
/// or `<request> SP missing`. Returns the size of an existing blob.
fn read_batch_check_record(reader: &mut dyn std::io::BufRead) -> Result<Option<u64>> {
    let mut line = Vec::new();
    if reader.read_until(b'\n', &mut line)? == 0 {
        return Err(Error::Git(
            "git cat-file ended before answering every request".to_string(),
        ));
    }
    let line = String::from_utf8_lossy(&line);
    let line = line.trim_end_matches('\n');
    if line.ends_with(" missing") {
        return Ok(None);
    }
    let mut fields = line.rsplit(' ');
    let size = fields.next().and_then(|s| s.parse::<u64>().ok());
    let kind = fields.next();
    // Only blobs have content worth probing.
    Ok(match (kind, size) {
        (Some("blob"), Some(size)) => Some(size),
        _ => None,
    })
}

/// Read one `git cat-file --batch` record, keeping at most `cap` content bytes.
///
/// A record is `<oid> SP <type> SP <size> LF <contents> LF`, or
/// `<request> SP missing LF` when the object does not exist. The unwanted
/// tail is drained rather than buffered, so memory stays bounded by `cap`
/// however large the blob is.
fn read_batch_record(reader: &mut dyn std::io::BufRead, cap: usize) -> Result<Option<Vec<u8>>> {
    use std::io::Read as _;

    let mut header = Vec::new();
    if reader.read_until(b'\n', &mut header)? == 0 {
        return Err(Error::Git(
            "git cat-file ended before answering every request".to_string(),
        ));
    }
    let header = String::from_utf8_lossy(&header);
    let header = header.trim_end_matches('\n');
    if header.ends_with(" missing") {
        return Ok(None);
    }
    // `<oid> <type> <size>` — the size is the last field.
    let size: u64 = header
        .rsplit(' ')
        .next()
        .and_then(|s| s.parse().ok())
        .ok_or_else(|| Error::Git(format!("unparsable git cat-file record: {header}")))?;

    // `min` bounds this by `cap`, so the conversion back cannot lose anything.
    let take = size.min(cap as u64);
    let mut blob = Vec::with_capacity(usize::try_from(take).unwrap_or(cap));
    reader.take(take).read_to_end(&mut blob)?;
    // Drain the rest of the content plus the trailing newline.
    std::io::copy(&mut reader.take(size - take + 1), &mut std::io::sink())?;
    Ok(Some(blob))
}

/// Whether `path` uses a Windows extended-length (`\\?\`) prefix.
///
/// Git for Windows cannot parse that form. Always false on other platforms —
/// [`std::path::Prefix`] variants are simply never produced there.
fn is_verbatim(path: &Path) -> bool {
    use std::path::{Component, Prefix};
    matches!(
        path.components().next(),
        Some(Component::Prefix(prefix))
            if matches!(
                prefix.kind(),
                Prefix::Verbatim(_) | Prefix::VerbatimDisk(_) | Prefix::VerbatimUNC(..)
            )
    )
}

/// Git environment variables that select a *different* repository.
///
/// Left in place, the ambient environment silently redirects every git call:
/// `check --staged` would inspect a foreign index (letting this repo's staged
/// plaintext through) and `install` would drop the hook into a foreign repo.
/// Repository selection must come from the resolved `--repo`, nothing else.
///
/// This is `git rev-parse --local-env-vars` plus a few discovery knobs, minus
/// `GIT_INDEX_FILE` — see [`Repo::git_command`] for why that one is kept and
/// validated instead. Keep in sync with new git releases.
const GIT_REPO_ENV_VARS: &[&str] = &[
    "GIT_ALTERNATE_OBJECT_DIRECTORIES",
    "GIT_CEILING_DIRECTORIES",
    "GIT_COMMON_DIR",
    "GIT_CONFIG",
    "GIT_CONFIG_COUNT",
    "GIT_CONFIG_PARAMETERS",
    "GIT_DIR",
    "GIT_DISCOVERY_ACROSS_FILESYSTEM",
    "GIT_GRAFT_FILE",
    "GIT_IMPLICIT_WORK_TREE",
    "GIT_NAMESPACE",
    "GIT_NO_REPLACE_OBJECTS",
    "GIT_OBJECT_DIRECTORY",
    "GIT_PREFIX",
    "GIT_REPLACE_REF_BASE",
    "GIT_SHALLOW_FILE",
    "GIT_WORK_TREE",
];

/// A working `git` binary is a hard requirement for opening a repository.
///
/// Every boundary git-se enforces — the worktree top level, the per-worktree
/// git dir, the common dir, "is this path inside a git dir" — is answered by
/// git plumbing. When git was missing, those lookups silently fell back to
/// path-shape guesses, and a `--separate-git-dir` layout (no `.git` anywhere
/// in its path) slipped past all of them: `git-se --repo <gitdir>/refs
/// encrypt --allow-password-change` encrypted real refs (H-08). Refuse to
/// open instead; `--allow-password-change` only ever skips the *password*
/// anchor check, never repository identity verification.
fn ensure_git_available() -> Result<()> {
    let mut cmd = std::process::Command::new("git");
    cmd.arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .env_remove(crate::utils::PASSWORD_ENV_VAR);
    for var in GIT_REPO_ENV_VARS {
        cmd.env_remove(var);
    }
    match cmd.status() {
        Ok(status) if status.success() => Ok(()),
        Ok(status) => Err(Error::GitUnavailable(format!(
            "`git --version` exited with {status}"
        ))),
        Err(e) => Err(Error::GitUnavailable(e.to_string())),
    }
}

/// Hard boundary (H-02): never treat anything inside a git dir as a
/// repository root. `<repo>/.git/refs` *is* inside a valid repository — git
/// would happily answer questions about it while every path underneath got
/// treated as ordinary content and encrypted, destroying the repo.
///
/// Pins the worktree top level through git plumbing when possible
/// (`repo_path` is updated in place); the content-shape fingerprint is only
/// a backstop for when plumbing cannot confirm the repository's identity.
fn reject_paths_inside_git_dir(repo_path: &mut PathBuf) -> Result<()> {
    // The lexical check comes first: it does not depend on any plumbing
    // answer being unambiguous.
    if crate::utils::has_git_component(repo_path) {
        return Err(Error::PathInsideGitDir(repo_path.clone()));
    }
    match rev_parse_flag(repo_path, "--is-inside-git-dir").as_deref() {
        Some("true") => return Err(Error::PathInsideGitDir(repo_path.clone())),
        Some(_) => {}
        None => debug!("`{}` is not inside a git repository", repo_path.display()),
    }

    // Pin the worktree top level via plumbing instead of trusting the shape
    // of the caller's path. Absent outside a repository, in which case the
    // given path stands (the historical behavior).
    let toplevel = rev_parse_path(repo_path, "--show-toplevel");
    let plumbing_confirmed = toplevel.is_some();
    if let Some(top) = toplevel {
        *repo_path = top;
    }

    // Content-shape backstop (H-08), only when git plumbing could NOT
    // confirm a worktree: a `--separate-git-dir` layout has no `.git`
    // anywhere in its path, so the lexical check cannot see it and an
    // ambiguous plumbing answer would wave a detached git dir through. HEAD
    // next to objects/ and refs/ is a git dir's fingerprint. When git DID
    // identify the worktree, git itself is the authority on what is a git
    // dir — a worktree that legitimately contains such entries must open
    // fine (2026-07 audit false positive). (A bare repo matches the
    // fingerprint too, but `--is-inside-git-dir` already answered true
    // there and rejected it above.)
    if !plumbing_confirmed {
        for ancestor in repo_path.ancestors() {
            if looks_like_git_dir(ancestor) {
                return Err(Error::PathInsideGitDir(repo_path.clone()));
            }
        }
    }
    Ok(())
}

/// Whether `path` has the content shape of a git dir: a `HEAD` file next to
/// `objects/` and `refs/`. A `--separate-git-dir` layout need not contain
/// `.git` anywhere in its path, so this fingerprint catches what the lexical
/// check cannot. (A bare repo matches too — it has no worktree, so opening
/// it as one would expose git internals as ordinary files.)
fn looks_like_git_dir(path: &Path) -> bool {
    path.join("HEAD").is_file() && path.join("objects").is_dir() && path.join("refs").is_dir()
}

/// Validate the config file's filesystem shape before it is read.
///
/// The config decides the security policy, so it is held to the same
/// standard as a target file (the README's promise): a real file inside
/// the repository — never a symlink, never resolving into a git dir.
/// `symlink_metadata`, not `exists`: a dangling symlinked config must be
/// rejected, not silently ignored.
fn validate_config_file(config_file_path: &Path, canonical: &Path) -> Result<()> {
    match std::fs::symlink_metadata(config_file_path) {
        Ok(meta) if meta.file_type().is_symlink() => {
            Err(Error::SymlinkedTarget(config_file_path.to_path_buf()))
        }
        Ok(meta) if meta.is_file() => {
            // The config is read before any target validation runs, so it
            // needs the boundary check applied to it directly: a symlinked
            // config was followed out of the repository and its crypt list
            // used, despite the "never reads outside the repo" guarantee.
            let real = dunce::canonicalize(config_file_path)
                .unwrap_or_else(|_| config_file_path.to_path_buf());
            if !real.starts_with(canonical) {
                return Err(Error::PathEscapesRepo(real));
            }
            // strip_prefix is guaranteed by the starts_with check above.
            let config_rel = real.strip_prefix(canonical).unwrap();
            if crate::utils::has_git_component(config_rel) {
                return Err(Error::ProtectedPath(config_file_path.to_path_buf()));
            }
            Ok(())
        }
        Ok(_) => Ok(()), // a directory etc. at that path fails the TOML load
        Err(_) => {
            warn!(
                "Config file not found: `{}`, using default config instead...",
                config_file_path.display()
            );
            Ok(())
        }
    }
}

/// Phase two of nested-repository protection: confirm what the discovery
/// scan found and merge it into the protected set.
///
/// A directory with the git-dir HEAD shape but WITHOUT the `config`
/// evidence every git-created git dir carries cannot be told apart from
/// ordinary allowlisted data — and git tracks such contents without
/// complaint. Guessing "git dir" silently hides tracked plaintext from the
/// crypt list (and from `check --staged`); guessing "data" could shred a
/// repository. Refuse to guess. Git dirs under arbitrary names (pointer
/// targets, bare repos) join the protected set only once the INDEX proves
/// nothing beneath them is tracked (2026-07 audit).
fn confirm_nested_git_dirs(
    nested: crate::utils::NestedGitDirs,
    repo_path: &Path,
    canonical: &Path,
    protected_dirs: &mut crate::utils::ProtectedDirs,
) -> Result<()> {
    for dir in nested.confirmed {
        protected_dirs.insert(dir, canonical);
    }
    if let Some(dir) = nested.ambiguous.first() {
        return Err(Error::AmbiguousGitDir(
            dir.clone(),
            "it lacks the `config` evidence (`[core]` `bare`/`worktree`) a real git dir carries",
        ));
    }
    for dir in &nested.needs_index_check {
        let rel = dir.strip_prefix(canonical).unwrap_or(dir.as_path());
        if index_tracks_any(repo_path, rel)? {
            return Err(Error::AmbiguousGitDir(
                dir.clone(),
                "this repository tracks files beneath it, so it may be ordinary allowlisted data",
            ));
        }
        protected_dirs.insert(dir.clone(), canonical);
    }
    Ok(())
}

/// Whether the repository's index tracks at least one path under `rel` (a
/// repo-relative directory prefix).
///
/// Nested-git-dir candidates under arbitrary names may only be protected
/// when the index proves they are NOT ordinary tracked data (2026-07
/// audit): git tracks HEAD/objects/refs-shaped contents without complaint,
/// so a candidate the repository tracks is allowlisted content — hiding it
/// behind nested-repository protection would leave tracked plaintext
/// unencrypted while `check --staged` waves the commit through.
///
/// Fail-closed: when git cannot answer although this genuinely is a
/// repository, the error propagates — "cannot tell" must never read as
/// "tracks nothing". A plain (non-git) directory has no index at all, so
/// nothing can be tracked there.
fn index_tracks_any(repo_path: &Path, rel: &Path) -> Result<bool> {
    use std::io::Read as _;
    let mut cmd = std::process::Command::new("git");
    cmd.current_dir(repo_path)
        // `--literal-pathspecs`: the prefix is a real directory name, never
        // a glob — a `*` in its name must not match other files.
        .args([
            "--no-replace-objects",
            "--literal-pathspecs",
            "ls-files",
            "-z",
            "--",
        ])
        .arg(rel.as_os_str())
        .env_remove(crate::utils::PASSWORD_ENV_VAR);
    for var in GIT_REPO_ENV_VARS {
        cmd.env_remove(var);
    }
    let mut child = cmd
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .spawn()?;
    // Only the FIRST byte matters ("is there any tracked path?"): read one,
    // then kill git rather than streaming a potentially huge listing.
    let mut first = [0u8; 1];
    let read = child
        .stdout
        .take()
        .map(|mut stdout| stdout.read(&mut first));
    let _ = child.kill(); // no-op when git already exited (no matches)
    let status = child.wait()?;
    if matches!(read, Some(Ok(1))) {
        return Ok(true);
    }
    if let Some(Err(e)) = read {
        return Err(e.into());
    }
    if !status.success() {
        // A plain (non-git) directory has no index: nothing can be tracked.
        // A real repository whose index cannot be read must fail closed.
        let is_repo = rev_parse_flag(repo_path, "--is-inside-work-tree").as_deref() == Some("true");
        if is_repo {
            return Err(Error::Git(format!(
                "could not list the index to check {} for tracked files",
                rel.display()
            )));
        }
    }
    Ok(false)
}

/// Run `git rev-parse <flag>` in `repo_path` and return the trimmed stdout.
///
/// Uses the same sanitized environment as every other git call, so the
/// repository being described cannot be swapped out from under us.
fn rev_parse_flag(repo_path: &Path, flag: &str) -> Option<String> {
    let mut cmd = std::process::Command::new("git");
    cmd.current_dir(repo_path)
        .args(["--no-replace-objects", "rev-parse", flag])
        .env_remove(crate::utils::PASSWORD_ENV_VAR);
    for var in GIT_REPO_ENV_VARS {
        cmd.env_remove(var);
    }
    let output = cmd.output().ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = String::from_utf8(output.stdout).ok()?;
    let trimmed = stdout.trim();
    if trimmed.is_empty() {
        return None;
    }
    Some(trimmed.to_owned())
}

/// [`rev_parse_flag`], interpreted as a canonical absolute path.
fn rev_parse_path(repo_path: &Path, flag: &str) -> Option<PathBuf> {
    let trimmed = rev_parse_flag(repo_path, flag)?;
    // `--git-common-dir` may print a path relative to the current dir;
    // absolutize against the repo path (a no-op when already absolute).
    let path = Path::new(&trimmed).absolutize_from(repo_path).into_owned();
    // Canonicalize so the result is in real-path form regardless of
    // whether git printed a relative or absolute path — git resolves
    // symlinks (e.g. macOS /var -> /private/var) but the repo path may
    // still contain them.
    //
    // `dunce`, not `std`: on Windows `std::fs::canonicalize` returns an
    // extended-length `\\?\C:\...` path. These values are handed straight
    // back to git as `--git-dir` / `--work-tree`, and git cannot parse that
    // form — it fails with "unknown error occurred while reading the
    // configuration files". They would also show up in user-facing output.
    Some(dunce::canonicalize(&path).unwrap_or(path))
}

/// Resolve the per-worktree git dir and the common git dir for `repo_path`
/// via `git rev-parse`.
///
/// Both fall back gracefully when the directory is not a git repository:
/// `git_dir` falls back to `<repo>/.git` (the historical behavior) and
/// `git_common_dir` falls back to `git_dir`. (`git` itself is never missing:
/// [`Repo::open`] fails with [`Error::GitUnavailable`] first.)
fn resolve_git_dirs(repo_path: &Path) -> (PathBuf, PathBuf) {
    let git_dir =
        rev_parse_path(repo_path, "--absolute-git-dir").unwrap_or_else(|| repo_path.join(".git"));
    let git_common_dir =
        rev_parse_path(repo_path, "--git-common-dir").unwrap_or_else(|| git_dir.clone());
    debug!(
        "git dir: {}, common git dir: {}",
        git_dir.display(),
        git_common_dir.display()
    );
    (git_dir, git_common_dir)
}

#[cfg(test)]
mod tests {
    use std::process::Command;

    use path_absolutize::Absolutize;
    use tempfile::TempDir;

    use super::*;

    #[test]
    fn test_repo_open() -> Result<()> {
        let repo = Repo::open(Path::new(".").absolutize()?)?;
        assert_eq!(repo.path().file_name().unwrap(), "git-simple-encrypt");
        let repo = Repo::open(Path::new("./.git").absolutize()?)?;
        assert_eq!(repo.path().file_name().unwrap(), "git-simple-encrypt");
        Ok(())
    }

    fn init_temp_repo() -> TempDir {
        let dir = TempDir::new().unwrap();
        // `git init` so that .git/ exists for hook installation & config.
        Command::new("git")
            .args(["init"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        dir
    }

    #[test]
    fn test_set_get_config_roundtrip() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        repo.set_config("key", "hunter2")?;
        let read_back = repo.get_config("key")?;
        assert_eq!(read_back.as_str(), "hunter2");
        Ok(())
    }

    #[test]
    fn test_scrub_legacy_key() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        // Simulate a password stored by an older version. (The automatic
        // scrub on `Repo::open` is disabled under cfg(test), so call it
        // explicitly here.)
        repo.set_config("key", "hunter2")?;
        assert!(repo.get_config("key").is_ok());

        repo.scrub_legacy_key();
        assert!(repo.get_config("key").is_err());

        // Idempotent: scrubbing again is a no-op.
        repo.scrub_legacy_key();
        Ok(())
    }

    #[test]
    fn test_install_hook_creates_file() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        repo.install_hook()?;
        let hook = repo_path.join(".git").join("hooks").join("pre-commit");
        assert!(hook.exists());
        let content = std::fs::read(&hook)?;
        assert!(
            content.starts_with(b"#!/bin/sh"),
            "hook should be a shell script"
        );

        // Second install must fail (idempotency guard).
        let second = repo.install_hook();
        assert!(matches!(second, Err(Error::HookExists(_))));
        Ok(())
    }

    /// Regression (2026-07 audit): `install` must not follow a dangling
    /// symlink at the hook path — `exists()` reported it absent while
    /// `fs::write` would have created the link's TARGET, possibly outside
    /// the repository.
    #[cfg(unix)]
    #[test]
    fn test_install_hook_refuses_dangling_symlink() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;
        let outside = repo_path.join("outside-hook-target");
        std::os::unix::fs::symlink(&outside, repo_path.join(".git/hooks/pre-commit"))?;

        let result = repo.install_hook();
        assert!(
            matches!(result, Err(Error::HookExists(_))),
            "a dangling symlink at the hook path must read as 'exists', got {result:?}"
        );
        assert!(
            !outside.exists(),
            "the write must never follow the symlink to its target"
        );
        Ok(())
    }

    #[test]
    fn test_worktree_git_dir_resolution() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();

        // A commit is required before `git worktree add`.
        std::fs::write(repo_path.join("f.txt"), "x")?;
        Command::new("git")
            .args(["add", "f.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        let commit = Command::new("git")
            .args([
                "-c",
                "user.email=t@example.com",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "init",
            ])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(commit.status.success(), "commit failed: {commit:?}");

        let wt_parent = TempDir::new().unwrap();
        let wt_path = wt_parent.path().join("wt");
        let out = Command::new("git")
            .args(["worktree", "add", wt_path.to_str().unwrap()])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(out.status.success(), "worktree add failed: {out:?}");

        let wt_repo = Repo::open(&wt_path)?;
        assert!(
            wt_repo.git_dir().ends_with(".git/worktrees/wt"),
            "unexpected worktree git dir: {}",
            wt_repo.git_dir().display()
        );
        // git reports real paths (symlinks resolved, e.g. macOS
        // /var -> /private/var), so compare canonicalized forms.
        assert_eq!(
            wt_repo.git_common_dir,
            dunce::canonicalize(repo_path.join(".git"))?
        );

        // The hook must land in the *common* dir so it fires for all worktrees.
        wt_repo.install_hook()?;
        assert!(repo_path.join(".git/hooks/pre-commit").exists());
        Ok(())
    }

    /// Opening a repo through a symlinked path must still yield canonical
    /// git dirs (macOS: /var -> /private/var; this reproduces it on Linux).
    #[cfg(unix)]
    #[test]
    fn test_repo_open_via_symlinked_path() -> Result<()> {
        let dir = init_temp_repo();
        let link_parent = TempDir::new().unwrap();
        let link = link_parent.path().join("repo-link");
        std::os::unix::fs::symlink(dir.path(), &link)?;

        let repo = Repo::open(&link)?;
        let expected = dunce::canonicalize(dir.path().join(".git"))?;
        assert_eq!(repo.git_dir(), &expected);
        assert_eq!(repo.git_common_dir, expected);
        Ok(())
    }

    #[test]
    fn test_check_reports_unencrypted() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let mut repo = Repo::open(&repo_path)?;

        // Add a plaintext file to the crypt list.
        std::fs::write(repo_path.join("plain.txt"), b"hello")?;
        repo.conf
            .add_one_path_to_crypt_list("plain.txt", &repo.protected())?;

        // check should return FilesNotEncrypted.
        let result = repo.check(&[], false);
        assert!(matches!(result, Err(Error::FilesNotEncrypted(1, 1))));

        // A bare header is NOT enough (M-01): without a complete chunk the
        // file cannot be real ciphertext, so the check must keep failing.
        let header = crate::crypt::FileHeader::new(false, [0x11; 16], [0x22; 16]);
        std::fs::write(repo_path.join("plain.txt"), header.as_bytes()).unwrap();
        let result = repo.check(&[], false);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "a header with no chunk must not pass as encrypted: {result:?}"
        );

        // A header followed by a complete minimal chunk does pass the format
        // check (it cannot be authenticated without the password).
        std::fs::write(repo_path.join("plain.txt"), fake_encrypted_blob(&header))?;
        assert!(repo.check(&[], false).is_ok());
        Ok(())
    }

    /// A byte string that satisfies the format check: a valid header plus one
    /// complete (garbage) chunk. Only the *format* is valid — there is no
    /// password behind it, which is exactly what the format check can't tell.
    #[cfg(test)]
    fn fake_encrypted_blob(header: &crate::crypt::FileHeader) -> Vec<u8> {
        let mut blob = header.as_bytes().to_vec();
        blob.extend_from_slice(&[0u8; crate::crypt::NONCE_LEN + 16]);
        blob
    }

    /// Regression (H-01): `check --staged` must inspect the staged blob, not
    /// the working-tree file. Stage plaintext, then encrypt the working tree:
    /// the check must still fail because the index holds plaintext.
    #[test]
    fn test_check_staged_reads_index_blob() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let mut repo = Repo::open(&repo_path)?;

        std::fs::write(repo_path.join("s.txt"), b"PLAINTEXT")?;
        repo.conf
            .add_one_path_to_crypt_list("s.txt", &repo.protected())?;

        // Stage the plaintext version.
        Command::new("git")
            .args(["add", "s.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();

        // Now the working tree gets an encrypted-looking file.
        let header = crate::crypt::FileHeader::new(false, [0x11; 16], [0x22; 16]);
        std::fs::write(repo_path.join("s.txt"), fake_encrypted_blob(&header))?;

        // The staged blob is still plaintext — check must fail even though
        // the working tree looks encrypted.
        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "staged plaintext must fail even with encrypted worktree: {result:?}"
        );

        // Stage the encrypted version too → now the index is encrypted.
        Command::new("git")
            .args(["add", "s.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(repo.check(&[], true).is_ok());
        Ok(())
    }

    /// Regression (H-01): a file staged as plaintext and then deleted from
    /// the working tree must still be caught (the staged blob is what gets
    /// committed).
    #[test]
    fn test_check_staged_deleted_worktree() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let mut repo = Repo::open(&repo_path)?;

        std::fs::write(repo_path.join("s.txt"), b"PLAINTEXT")?;
        repo.conf
            .add_one_path_to_crypt_list("s.txt", &repo.protected())?;
        Command::new("git")
            .args(["add", "s.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();

        // Delete the working-tree file after staging plaintext.
        std::fs::remove_file(repo_path.join("s.txt"))?;

        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "deleted-from-worktree staged plaintext must fail: {result:?}"
        );
        Ok(())
    }

    /// Write a config file with the given crypt list and return the repo.
    fn repo_with_crypt_list(repo_path: &Path, entries: &[&str]) -> Result<Repo> {
        let list = entries
            .iter()
            .map(|e| format!("{e:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        std::fs::write(
            repo_path.join(CONFIG_FILE_NAME),
            format!("use_zstd = true\nzstd_level = 15\ncrypt_list = [{list}]\n"),
        )?;
        Repo::open(repo_path)
    }

    fn git(args: &[&str], pwd: &Path) {
        let out = Command::new("git")
            .args(args)
            .current_dir(pwd)
            .output()
            .unwrap();
        assert!(out.status.success(), "git {args:?} failed: {out:?}");
    }

    /// Regression (H-01): a crypt-list *directory* that no longer exists in
    /// the working tree must still cover its staged blobs. The old
    /// `repo.join(entry).is_dir()` test silently unlisted every one of them.
    #[test]
    fn test_check_staged_directory_deleted_from_worktree() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        std::fs::create_dir(repo_path.join("secrets"))?;
        std::fs::write(repo_path.join("secrets/a.txt"), b"PLAINTEXT")?;
        let repo = repo_with_crypt_list(&repo_path, &["secrets"])?;

        git(&["add", "-A"], &repo_path);
        std::fs::remove_dir_all(repo_path.join("secrets"))?;

        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "staged blobs under a deleted crypt-list dir must be checked: {result:?}"
        );
        Ok(())
    }

    /// Regression (H-01): a committed symlink replaced by a plaintext regular
    /// file is a typechange (`T`), which the old `--diff-filter=ACMR` dropped.
    #[cfg(unix)]
    #[test]
    fn test_check_staged_typechange() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        // A repo-relative (and deliberately dangling) target: git stores the
        // link text as the blob, so what it points at is irrelevant, and this
        // avoids assuming any particular system file exists.
        std::os::unix::fs::symlink("link-target", repo_path.join("s.txt"))?;
        let repo = repo_with_crypt_list(&repo_path, &["s.txt"])?;

        git(&["add", "-A"], &repo_path);
        git(
            &[
                "-c",
                "user.email=t@e.com",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "init",
            ],
            &repo_path,
        );

        // symlink -> regular plaintext file
        std::fs::remove_file(repo_path.join("s.txt"))?;
        std::fs::write(repo_path.join("s.txt"), b"PLAINTEXT_SECRET")?;
        git(&["add", "s.txt"], &repo_path);

        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "a symlink->regular typechange must be checked: {result:?}"
        );
        Ok(())
    }

    /// Regression (H-01): the policy must come from the *index* copy of the
    /// config. Emptying `crypt_list` in the working tree without staging it
    /// used to disable the check for a commit that still demanded encryption.
    #[test]
    fn test_check_staged_uses_index_config() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        std::fs::write(repo_path.join("secret.txt"), b"PLAINTEXT_SECRET")?;
        repo_with_crypt_list(&repo_path, &["secret.txt"])?;
        git(&["add", "-A"], &repo_path);

        // Working tree now says "encrypt nothing" — but that is NOT staged.
        let repo = repo_with_crypt_list(&repo_path, &[])?;
        assert!(repo.conf.crypt_list.is_empty());

        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "the staged config must decide the policy: {result:?}"
        );
        Ok(())
    }

    /// Regression: with the whole-repo entry `.`, the config file itself must
    /// not be demanded encrypted — it is excluded from encryption, so the
    /// check would have been permanently unsatisfiable.
    #[test]
    fn test_check_staged_dot_entry_excludes_config() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = repo_with_crypt_list(&repo_path, &["."])?;
        git(&["add", CONFIG_FILE_NAME], &repo_path);

        assert!(
            repo.check(&[], true).is_ok(),
            "the git-se config must never be checked for encryption"
        );
        Ok(())
    }

    /// An unrecovered transaction journal must fail `Repo::open` CLOSED:
    /// running commands on a partially recovered tree would proceed from a
    /// mixed state (e.g. old- and new-password ciphertext side by side after
    /// an interrupted password change).
    #[test]
    fn test_repo_open_fails_closed_on_unrecovered_journal() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();

        // Craft a v3 journal whose restore fails: a non-empty directory sits
        // at the destination, so renaming the backup over it fails.
        let dst = repo_path.join("a");
        std::fs::create_dir(&dst)?;
        std::fs::write(dst.join("occupied"), b"x")?;
        let backup = repo_path.join(".git-se-bak.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.0");
        std::fs::write(&backup, b"OLD_A")?;
        let journal = crate::crypt::journal_path(&repo_path.join(".git"));
        let mut record = b"v3\0".to_vec();
        record.extend_from_slice(b"a");
        record.push(0);
        record.extend_from_slice(b".git-se-bak.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.0".as_slice());
        record.push(0);
        crate::utils::atomic_write(&journal, &record)?;

        let result = Repo::open(&repo_path);
        assert!(
            matches!(result, Err(Error::RecoveryIncomplete(_, _))),
            "expected RecoveryIncomplete, got {result:?}"
        );

        // Removing the obstruction lets the next open recover and proceed.
        std::fs::remove_dir_all(&dst)?;
        let repo = Repo::open(&repo_path)?;
        drop(repo);
        assert_eq!(std::fs::read(&dst)?, b"OLD_A");
        assert!(!journal.exists());
        Ok(())
    }

    /// Regression (2026-07 audit): a journal that exists but cannot be READ
    /// (here: a directory at its path) must fail `Repo::open` closed. It
    /// used to read as "no transaction", so commands ran on a possibly
    /// half-recovered tree — and the startup sweep could delete the backups
    /// that are the last recovery material.
    #[test]
    fn test_repo_open_fails_closed_on_unreadable_journal() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let journal = crate::crypt::journal_path(&repo_path.join(".git"));
        std::fs::create_dir(&journal)?;

        let result = Repo::open(&repo_path);
        assert!(
            matches!(result, Err(Error::JournalUnreadable(_, _))),
            "expected JournalUnreadable, got {result:?}"
        );
        assert!(journal.is_dir(), "the unreadable journal must be kept");

        // Removing the obstruction lets the next open proceed.
        std::fs::remove_dir(&journal)?;
        drop(Repo::open(&repo_path)?);
        Ok(())
    }

    /// A corrupt journal (unknown version / truncated) must fail
    /// `Repo::open` closed too — and survive for manual inspection.
    #[test]
    fn test_repo_open_fails_closed_on_corrupt_journal() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let journal = crate::crypt::journal_path(&repo_path.join(".git"));
        crate::utils::atomic_write(&journal, b"v9\0a\0b\0")?;

        let result = Repo::open(&repo_path);
        assert!(
            matches!(result, Err(Error::JournalCorrupt(_))),
            "expected JournalCorrupt, got {result:?}"
        );
        assert!(journal.exists(), "a corrupt journal must be kept");
        Ok(())
    }

    /// Build a bare-repository-shaped directory: the git-dir structure plus
    /// the `[core] bare = true` config evidence every git-created git dir
    /// carries.
    fn make_bare_repo_shape(dir: &Path) {
        std::fs::create_dir_all(dir.join("objects")).unwrap();
        std::fs::create_dir_all(dir.join("refs")).unwrap();
        std::fs::write(dir.join("HEAD"), b"ref: refs/heads/main\n").unwrap();
        std::fs::write(dir.join("config"), b"[core]\n\tbare = true\n").unwrap();
    }

    /// Regression (2026-07 audit, high): git tracks HEAD/objects/refs-shaped
    /// contents as ordinary files without complaint, so a TRACKED
    /// git-shaped directory is ordinary allowlisted data — never a nested
    /// repository to hide behind. Silently protecting it used to leave
    /// `data/objects/payload` (inside `crypt_list = ["."]`) unencrypted
    /// while `check --staged` waved the plaintext commit through. Opening
    /// must refuse to guess instead.
    #[test]
    fn test_repo_open_rejects_tracked_git_shaped_dir() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        make_bare_repo_shape(&repo_path.join("data"));
        std::fs::write(repo_path.join("data/objects/payload"), b"SUPER SECRET")?;
        git(&["add", "-A"], &repo_path);

        // The files are staged (tracked) — the state in which the silent
        // protection used to let plaintext be committed.
        let tracked = Command::new("git")
            .args(["ls-files", "--", "data"])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(!tracked.stdout.is_empty(), "setup: data/ is tracked");

        let result = Repo::open(&repo_path);
        assert!(
            matches!(result, Err(Error::AmbiguousGitDir(_, _))),
            "a tracked git-shaped directory must fail the open, got {result:?}"
        );

        // Untracked, the very same shape is a genuine nested bare
        // repository: protected again, and the payload stays untouched.
        git(&["rm", "-r", "-q", "--cached", "data"], &repo_path);
        let repo = Repo::open(&repo_path)?;
        let err = crate::utils::validate_repo_relative(
            Path::new("data/objects/payload"),
            &repo.protected(),
        )
        .unwrap_err();
        assert!(
            matches!(err, Error::ProtectedPath(_)),
            "an untracked bare repo stays protected, got {err:?}"
        );
        assert_eq!(
            std::fs::read(repo_path.join("data/objects/payload"))?,
            b"SUPER SECRET"
        );
        Ok(())
    }

    /// Regression (2026-07 audit): the git-dir SHAPE without the `config`
    /// evidence a real git dir carries is ambiguous — ordinary data or a
    /// repository, and guessing either way is wrong. Opening must fail
    /// closed even when nothing beneath is tracked.
    #[test]
    fn test_repo_open_rejects_git_shape_without_config_evidence() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        std::fs::create_dir_all(repo_path.join("data/objects"))?;
        std::fs::create_dir_all(repo_path.join("data/refs"))?;
        std::fs::write(repo_path.join("data/HEAD"), b"ref: refs/app")?;

        let result = Repo::open(&repo_path);
        assert!(
            matches!(result, Err(Error::AmbiguousGitDir(_, _))),
            "git-shaped data without config evidence must fail the open, got {result:?}"
        );

        // Deleting one leg of the shape makes it ordinary data again.
        std::fs::remove_file(repo_path.join("data/HEAD"))?;
        drop(Repo::open(&repo_path)?);
        Ok(())
    }

    /// Regression (2026-07 audit): journal recovery shares the unified
    /// protected set. A journal (left by a vulnerable version, or hostile)
    /// naming a path inside a DISCOVERED nested git dir must be rejected as
    /// corrupt — recovery used to confine paths only against the outer
    /// git dir.
    #[test]
    fn test_repo_open_fails_closed_on_journal_into_nested_gitdir() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        make_bare_repo_shape(&repo_path.join("bare-repo"));
        // Open once so the nested bare repo is discovered and protected.
        let repo = Repo::open(&repo_path)?;
        let journal = crate::crypt::journal_path(repo.git_dir());
        drop(repo);

        std::fs::write(
            repo_path.join(".git-se-bak.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.0"),
            b"BACKUP",
        )?;
        let mut record = b"v3\0".to_vec();
        record.extend_from_slice(b"bare-repo/HEAD");
        record.push(0);
        record.extend_from_slice(b".git-se-bak.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.0");
        record.push(0);
        crate::utils::atomic_write(&journal, &record)?;

        let result = Repo::open(&repo_path);
        assert!(
            matches!(result, Err(Error::JournalCorrupt(_))),
            "a journal into a nested git dir must be rejected as corrupt, got {result:?}"
        );
        assert_eq!(
            std::fs::read(repo_path.join("bare-repo/HEAD"))?,
            b"ref: refs/heads/main\n",
            "recovery must never write into a nested git dir"
        );
        assert!(journal.exists(), "a corrupt journal must be kept");
        Ok(())
    }

    /// Regression (2026-07 audit): a perfectly normal worktree that happens
    /// to contain `HEAD`, `objects/` and `refs/` entries at its root must
    /// open fine — the git-dir fingerprint backstop only applies when git
    /// plumbing cannot confirm the repository's identity.
    #[test]
    fn test_repo_open_tolerates_git_dir_shaped_content() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        std::fs::write(repo_path.join("HEAD"), b"not git's HEAD")?;
        std::fs::create_dir_all(repo_path.join("objects"))?;
        std::fs::create_dir_all(repo_path.join("refs"))?;

        let repo = Repo::open(&repo_path)?;
        assert_eq!(
            dunce::canonicalize(repo.path())?,
            dunce::canonicalize(&repo_path)?,
            "a confirmed worktree must open despite the git-dir-shaped content"
        );
        Ok(())
    }

    /// Regression (H-02): a path inside the git dir is not a repository root.
    /// Accepting `<repo>/.git/refs` used to encrypt `refs/heads/*`, which
    /// destroys the repository.
    #[test]
    fn test_repo_open_rejects_paths_inside_git_dir() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();

        for inside in [".git/refs", ".git/objects", ".git/hooks"] {
            let path = repo_path.join(inside);
            std::fs::create_dir_all(&path)?;
            assert!(
                matches!(Repo::open(&path), Err(Error::PathInsideGitDir(_))),
                "{inside} must be rejected as a repo root"
            );
        }
        Ok(())
    }

    /// Regression (H-02): `.GIT` (an alias symlink, or a case-insensitive
    /// filesystem) must resolve to the worktree root, never to the git dir.
    #[cfg(unix)]
    #[test]
    fn test_repo_open_git_alias_resolves_to_worktree() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let alias = repo_path.join(".GIT");

        // On a case-insensitive filesystem (the macOS default) `.GIT` already
        // *is* `.git`, so creating the alias would fail with EEXIST — that
        // platform reaches the case under test natively. Elsewhere a symlink
        // reproduces the same shape.
        if !alias.exists() {
            std::os::unix::fs::symlink(".git", &alias)?;
        }

        let repo = Repo::open(&alias)?;
        assert_eq!(
            dunce::canonicalize(repo.path())?,
            dunce::canonicalize(&repo_path)?,
            "`.GIT` must open the worktree, not the git dir"
        );
        Ok(())
    }
}
