use std::path::{Path, PathBuf};

use config_file2::LoadConfigFile;
use log::{debug, info, warn};
use parking_lot::Mutex;
use path_absolutize::Absolutize;
use rayon::prelude::*;
use zeroize::Zeroizing;

use crate::{
    config::{CONFIG_FILE_NAME, Config},
    error::{Error, Result},
    utils::{
        Progress, crypt_list_matches, git_z_path, is_file_encrypted, prompt_password,
        resolve_target_files, style::Colorize,
    },
};

pub const GIT_CONFIG_PREFIX: &str =
    const_str::replace!(concat!(env!("CARGO_CRATE_NAME"), "."), "_", "-");

/// The pre-commit hook content that runs `git-se check --staged` before every
/// commit, so only files part of the current commit are checked.
const PRE_COMMIT_HOOK: &[u8] = br#"#!/bin/sh
# Auto-generated by git-se install
git-se check --staged
if [ $? -ne 0 ]; then
    echo "Please run 'git-se e' to encrypt them before committing."
    exit 1
fi
"#;

#[derive(Debug, Clone, Default)]
pub struct Repo {
    /// The absolute path of the opened repo.
    pub path: PathBuf,
    /// The resolved per-worktree git dir (`git rev-parse --absolute-git-dir`,
    /// canonicalized).
    ///
    /// Equals `<path>/.git` for a normal repository, but differs for linked
    /// worktrees (`<main>/.git/worktrees/<name>`) and submodules
    /// (`<superproject>/.git/modules/<name>`). Falls back to `<path>/.git`
    /// when `git` is unavailable or the directory is not a git repository.
    pub git_dir: PathBuf,
    /// The resolved common git dir (`git rev-parse --git-common-dir`,
    /// canonicalized), where hooks and shared config live. Equals
    /// [`Repo::git_dir`] unless this is a linked worktree.
    pub git_common_dir: PathBuf,
    pub conf: Config,
}

impl Repo {
    /// Open a repo. The `path` argument must be an absolute path.
    pub fn open(path: impl AsRef<Path>) -> Result<Self> {
        if !path.as_ref().is_absolute() {
            return Err(Error::RepoPathNotAbsolute(path.as_ref().to_path_buf()));
        }
        let mut repo_path = path.as_ref().to_path_buf();
        if !repo_path.exists() {
            return Err(Error::RepoNotFound(repo_path));
        }
        if !repo_path.is_dir() {
            return Err(Error::NotADirectory(repo_path));
        }
        // Convenience: `git-se -r <repo>/.git` means `<repo>`. Compared
        // case-insensitively so `.GIT` (a case-insensitive filesystem, or a
        // hand-made alias symlink) resolves the same way (H-02).
        if repo_path
            .file_name()
            .is_some_and(|name| name.eq_ignore_ascii_case(".git"))
        {
            repo_path.pop();
        }

        // Hard boundary (H-02): never treat anything inside a git dir as a
        // repository root. Checked BEFORE resolving the top level, because
        // `<repo>/.git/refs` *is* inside a valid repository — git would
        // happily answer questions about it while every path underneath got
        // treated as ordinary content and encrypted, destroying the repo.
        if rev_parse_flag(&repo_path, "--is-inside-git-dir").as_deref() == Some("true") {
            return Err(Error::PathInsideGitDir(repo_path));
        }

        // Pin the worktree top level via plumbing instead of trusting the
        // shape of the caller's path. Absent outside a repository, in which
        // case the given path stands (the historical behavior).
        if let Some(top) = rev_parse_path(&repo_path, "--show-toplevel") {
            repo_path = top;
        }

        info!("Open repo: {}", repo_path.display());
        let (git_dir, git_common_dir) = resolve_git_dirs(&repo_path);

        // Independent second guard, in case the plumbing lookups were
        // unavailable (no git binary, or a fallback git dir was assumed).
        let canonical = repo_path
            .canonicalize()
            .unwrap_or_else(|_| repo_path.clone());
        if canonical.starts_with(&git_dir) || canonical.starts_with(&git_common_dir) {
            return Err(Error::PathInsideGitDir(canonical));
        }

        let config_file_path = repo_path.join(CONFIG_FILE_NAME);
        if !config_file_path.exists() {
            warn!(
                "Config file not found: `{}`, using default config instead...",
                config_file_path.display()
            );
        }
        let conf = Config::load_or_default(&config_file_path)
            .map_err(|e| Error::Config(e.to_string()))?
            .with_repo_path(&repo_path);
        let repo = Self {
            path: repo_path,
            git_dir,
            git_common_dir,
            conf,
        };
        // Scrub passwords stored by older versions. Skipped in unit tests so
        // that running the test suite cannot touch a real repo's config.
        #[cfg(not(test))]
        repo.scrub_legacy_key();
        Ok(repo)
    }

    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// The per-worktree git dir (see [`Repo::git_dir`]).
    #[must_use]
    pub fn git_dir(&self) -> &Path {
        &self.git_dir
    }

    pub fn to_absolute_path(&self, path: impl AsRef<Path>) -> PathBuf {
        self.path.join(path.as_ref())
    }

    /// Change the master password: decrypt every listed file with the old
    /// password, then re-encrypt everything with the new one.
    ///
    /// The old password is taken from `GIT_SE_PASSWORD` when set, otherwise
    /// prompted; the new password is always prompted (twice, echo disabled).
    /// Nothing is persisted anywhere — the password only lives in memory for
    /// the duration of the operation.
    pub fn change_password_interactive(&self) -> Result<()> {
        let target_files =
            crate::utils::resolve_target_files(&[], &self.conf.crypt_list, self.path())?;
        let encrypted_count = target_files
            .iter()
            .filter(|f| crate::utils::is_file_encrypted(f).unwrap_or(false))
            .count();
        if encrypted_count == 0 {
            println!(
                "No encrypted files in the crypt list; nothing to re-encrypt. \
                 The password is set implicitly at the next `git-se e`."
            );
            return Ok(());
        }

        // Order matters (H-05): validate the old password IN MEMORY and
        // confirm the new password BEFORE any file is touched, so a mistyped
        // confirmation cannot cost anything.
        let old_key = crate::utils::get_password("Please input your OLD key: ")?;
        crate::crypt::precheck_password(
            &target_files,
            crate::crypt::Password::new(old_key.as_bytes()),
        )?;

        let new_key = prompt_password("Please input your NEW key: ")?;
        let confirm = prompt_password("Please confirm your NEW key: ")?;
        if new_key.as_str() != confirm.as_str() {
            return Err(Error::PasswordMismatch);
        }

        // One transaction: old ciphertext → new ciphertext per file, all
        // committed together. The plaintext only ever exists in temp files,
        // so a failure at any point leaves every file encrypted with the OLD
        // password rather than stranding the repo in plaintext or in a mix.
        crate::crypt::change_password(
            self,
            crate::crypt::Password::new(old_key.as_bytes()),
            crate::crypt::Password::new(new_key.as_bytes()),
        )?;
        info!("Master key changed; all listed files were re-encrypted.");
        Ok(())
    }

    /// One-time migration: versions that stored the password in the repo-local
    /// git config get it scrubbed. Best-effort; only logs on failure.
    pub fn scrub_legacy_key(&self) {
        let legacy_key = format!("{GIT_CONFIG_PREFIX}key");
        if self.get_config("key").is_err() {
            return;
        }
        if self.run(&["config", "--unset", &legacy_key]).is_ok() {
            warn!(
                "Removed the password stored in .git/config by an older git-se version; \
                 passwords are no longer persisted."
            );
        } else {
            warn!(
                "A password from an older git-se version is still stored in .git/config and \
                 could not be removed automatically; please run \
                 `git config --local --unset {legacy_key}`."
            );
        }
    }

    /// Check if all files in the crypt list (or given paths) are encrypted.
    ///
    /// When `staged` is true, only files staged for the current commit are
    /// checked, by intersecting staged files against the crypt list. This is
    /// used by the pre-commit hook to avoid checking the entire repo.
    ///
    /// Returns `Ok(())` if all files are encrypted, or an error summarizing
    /// which files are not encrypted. The process exits with a non-zero code
    /// when files are not encrypted, suitable for CI usage.
    pub fn check(&self, paths: &[PathBuf], staged: bool) -> Result<()> {
        if staged {
            return self.check_staged();
        }
        let target_files = resolve_target_files(paths, &self.conf.crypt_list, self.path())?;

        if target_files.is_empty() {
            return Err(Error::NoFile("check"));
        }

        println!(
            "\n{} {} {}",
            "Checking encryption status".bold(),
            format!("({} files)", target_files.len()).cyan(),
            ":".dimmed()
        );

        let pb = Progress::new(target_files.len(), "Check");
        let not_encrypted: Mutex<Vec<PathBuf>> = Mutex::new(Vec::new());

        target_files.par_iter().try_for_each(|f| -> Result<()> {
            if !is_file_encrypted(f)? {
                let mut list = not_encrypted.lock();
                let relative = pathdiff::diff_paths(f, &self.path).unwrap_or_else(|| f.clone());
                list.push(relative);
            }
            pb.inc(1);
            Ok(())
        })?;

        pb.finish_and_clear();

        let not_encrypted = not_encrypted.into_inner();
        let total = target_files.len();
        let encrypted_count = total - not_encrypted.len();

        if not_encrypted.is_empty() {
            println!(
                "\n{}: All {} files are encrypted.",
                "Check complete".bold(),
                total.to_string().green(),
            );
            Ok(())
        } else {
            println!(
                "\n{} files are {}:",
                not_encrypted.len().to_string().yellow(),
                "NOT encrypted".yellow()
            );
            for f in &not_encrypted {
                println!("  - {}", f.display());
            }

            println!(
                "\n{}: {}/{} files encrypted",
                "Check complete".bold(),
                encrypted_count.to_string().green(),
                total,
            );

            Err(Error::FilesNotEncrypted(not_encrypted.len(), total))
        }
    }

    /// The crypt list that governs the tree about to be committed.
    ///
    /// Read from the **index** copy of the config, not the working-tree copy:
    /// otherwise an unstaged edit that empties `crypt_list` would disable the
    /// check for a commit whose own config still demands encryption (H-01).
    /// The index holds every tracked file, so this also covers the common case
    /// where the config is simply unmodified.
    ///
    /// The result is the *union* with the working-tree list. `crypt_list` is
    /// an allowlist, so a union can only ever demand more encryption — the
    /// fail-closed direction. It also keeps the check working before the
    /// config has ever been committed.
    fn staged_crypt_list(&self) -> Vec<String> {
        let mut list = self.conf.crypt_list.clone();
        if let Ok(bytes) = self.run_with_output_bytes(&["show", &format!(":{CONFIG_FILE_NAME}")])
            && let Ok(text) = String::from_utf8(bytes)
        {
            match Config::parse_crypt_list(&text) {
                Ok(staged) => list.extend(staged),
                // Do not fail the commit over a config this build cannot
                // parse; the working-tree list still applies.
                Err(e) => warn!("Could not parse the staged config file: {e}"),
            }
        }
        list.sort_unstable();
        list.dedup();
        list
    }

    /// Staged-mode check (used by the pre-commit hook).
    ///
    /// The blobs staged in the **index** are inspected — i.e. the content a
    /// commit would actually contain — never the working-tree files. A
    /// plaintext staged blob therefore cannot hide behind an encrypted (or
    /// deleted) working-tree file.
    fn check_staged(&self) -> Result<()> {
        let crypt_list = self.staged_crypt_list();

        // `--diff-filter=d` (lowercase) excludes *only* deletions, so
        // typechanges (T), unmerged entries (U) and broken pairs (B) are all
        // covered. The old `ACMR` allowlist let a committed symlink swapped
        // for a plaintext regular file through untouched.
        //
        // `--raw` additionally yields the destination mode, which is how
        // symlinks and gitlinks get excluded; `-z` makes git print filenames
        // verbatim, NUL-separated and without C-style quoting, so non-ASCII
        // names are not mangled and silently skipped.
        let raw =
            self.run_with_output_bytes(&["diff", "--cached", "--raw", "-z", "--diff-filter=d"])?;

        let mut staged: Vec<PathBuf> = Vec::new();
        let mut unmerged: Vec<PathBuf> = Vec::new();
        for entry in parse_raw_z(&raw) {
            if !crypt_list_matches(&crypt_list, &entry.path) {
                continue;
            }
            match entry.kind {
                // `git show :<path>` cannot read an unmerged path (it lives at
                // stages 1/2/3), so its content is unverifiable. Fail closed.
                StagedKind::Unmerged => unmerged.push(entry.path),
                StagedKind::Regular => staged.push(entry.path),
                // Symlink blobs hold a target path and gitlinks hold a commit
                // id; neither is a file this tool encrypts.
                StagedKind::Other => {}
            }
        }

        if staged.is_empty() && unmerged.is_empty() {
            println!("No staged files need encryption check.");
            return Ok(());
        }

        println!(
            "\n{} {} {}",
            "Checking staged content".bold(),
            format!("({} files)", staged.len() + unmerged.len()).cyan(),
            ":".dimmed()
        );

        let total = staged.len() + unmerged.len();
        let pb = Progress::new(staged.len(), "Check");
        // Unmerged paths start out in the failure list: their content cannot
        // be read, and "unverifiable" must not read as "fine".
        let not_encrypted: Mutex<Vec<PathBuf>> = Mutex::new(unmerged);

        staged.par_iter().try_for_each(|rel| -> Result<()> {
            let mut spec = std::ffi::OsString::from(":");
            spec.push(rel.as_os_str());
            let blob = self.run_with_output_bytes_capped(
                &[std::ffi::OsStr::new("show"), spec.as_os_str()],
                crate::crypt::MIN_ENCRYPTED_LEN,
            )?;
            if !crate::crypt::is_encrypted_header(&blob) {
                not_encrypted.lock().push(rel.clone());
            }
            pb.inc(1);
            Ok(())
        })?;

        pb.finish_and_clear();

        let mut not_encrypted = not_encrypted.into_inner();
        not_encrypted.sort_unstable();
        let encrypted_count = total - not_encrypted.len();

        if not_encrypted.is_empty() {
            println!(
                "\n{}: All {} staged files are encrypted.",
                "Check complete".bold(),
                total.to_string().green(),
            );
            Ok(())
        } else {
            println!(
                "\n{} staged files are {} (in the index):",
                not_encrypted.len().to_string().yellow(),
                "NOT encrypted".yellow()
            );
            for f in &not_encrypted {
                println!("  - {}", f.display());
            }
            println!(
                "\n{}: {}/{} staged files encrypted",
                "Check complete".bold(),
                encrypted_count.to_string().green(),
                total,
            );
            Err(Error::FilesNotEncrypted(not_encrypted.len(), total))
        }
    }

    /// Install a pre-commit hook that runs `git-se check` before each commit.
    ///
    /// Creates `<git-common-dir>/hooks/pre-commit` with the check script.
    /// The common dir (not the per-worktree git dir) is used so the hook also
    /// works for linked worktrees. Fails if a hook already exists and is not
    /// managed by git-se.
    pub fn install_hook(&self) -> Result<()> {
        let hooks_dir = self.git_common_dir.join("hooks");
        std::fs::create_dir_all(&hooks_dir)?;

        let hook_path = hooks_dir.join("pre-commit");

        // Check if hook already exists
        if hook_path.exists() {
            return Err(Error::HookExists(hook_path));
        }

        std::fs::write(&hook_path, PRE_COMMIT_HOOK)?;

        // Set executable permission on unix. Windows users need Git for Windows
        // (msys-based) which executes the sh hook regardless of the executable
        // bit; a normal `write` is sufficient there.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&hook_path)?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&hook_path, perms)?;
        }

        println!(
            "{} pre-commit hook at {}",
            "Installed".green().bold(),
            hook_path.display()
        );
        Ok(())
    }

    /// Build a `git` command scoped to this repo.
    ///
    /// The master password is scrubbed from the inherited environment so that
    /// git itself, config helpers, and hooks can never see it.
    ///
    /// Repository selection is pinned to the dirs resolved in [`Repo::open`]:
    /// the ambient [`GIT_REPO_ENV_VARS`] are dropped and `--git-dir` /
    /// `--work-tree` are passed explicitly (command-line beats environment).
    /// Without this, `GIT_DIR=<other-repo>` silently redirected every call.
    fn git_command(&self) -> std::process::Command {
        let mut cmd = std::process::Command::new("git");
        cmd.current_dir(&self.path)
            .env_remove(crate::utils::PASSWORD_ENV_VAR);
        for var in GIT_REPO_ENV_VARS {
            cmd.env_remove(var);
        }

        // `GIT_INDEX_FILE` needs judgement rather than a blanket removal:
        // `git commit --only <paths>` builds a temporary index inside the git
        // dir and points the hook at it, so dropping it would make the
        // pre-commit check inspect the wrong index. Keep it only when it
        // really does live inside our git dir; anything else is a redirect.
        if let Some(index) = std::env::var_os("GIT_INDEX_FILE") {
            let inside = PathBuf::from(&index)
                .absolutize_from(&self.path)
                .canonicalize()
                .is_ok_and(|c| c.starts_with(&self.git_dir) || c.starts_with(&self.git_common_dir));
            if !inside {
                warn!("Ignoring GIT_INDEX_FILE: it points outside this repository's git dir");
                cmd.env_remove("GIT_INDEX_FILE");
            }
        }

        cmd.arg("--git-dir")
            .arg(&self.git_dir)
            .arg("--work-tree")
            .arg(&self.path);

        // Force English output in tests so we can match on stderr reliably.
        if cfg!(test) {
            cmd.env("LC_ALL", "C.UTF-8").env("LANGUAGE", "C.UTF-8");
        }
        cmd
    }

    /// Run a `git` command in the repo, discarding its stdout/stderr.
    pub fn run<S: AsRef<std::ffi::OsStr>>(&self, args: &[S]) -> Result<()> {
        let output = self.git_command().args(args).output()?;
        if !output.status.success() {
            return Err(Error::Git(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }
        Ok(())
    }

    /// Run a `git` command and return its stdout as a `String`.
    pub fn run_with_output<S: AsRef<std::ffi::OsStr>>(&self, args: &[S]) -> Result<String> {
        String::from_utf8(self.run_with_output_bytes(args)?)
            .map_err(|e| Error::Other(format!("git output not UTF-8: {e}")))
    }

    /// Run a `git` command and return its raw stdout bytes.
    ///
    /// Needed for `-z` output, which is NUL-separated and may contain
    /// non-UTF-8 filenames.
    pub fn run_with_output_bytes<S: AsRef<std::ffi::OsStr>>(&self, args: &[S]) -> Result<Vec<u8>> {
        let output = self.git_command().args(args).output()?;
        if !output.status.success() {
            return Err(Error::Git(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }
        Ok(output.stdout)
    }

    /// Run a `git` command, capturing at most `cap` bytes of stdout.
    ///
    /// The child is killed once `cap` bytes have been read, so this stays
    /// cheap even for huge blobs (e.g. `git show HEAD:large.bin` during the
    /// password pre-check). Because of the early kill, the exit status is
    /// meaningless and therefore ignored: callers must treat an empty result
    /// as "no usable output".
    pub(crate) fn run_with_output_bytes_capped<S: AsRef<std::ffi::OsStr>>(
        &self,
        args: &[S],
        cap: usize,
    ) -> Result<Vec<u8>> {
        use std::io::Read as _;
        let mut child = self
            .git_command()
            .args(args)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::null())
            .spawn()?;
        let mut buf = Vec::new();
        if let Some(stdout) = child.stdout.take() {
            stdout.take(cap as u64).read_to_end(&mut buf)?;
        }
        let _ = child.kill(); // no-op when git already exited (blob smaller than cap)
        let _ = child.wait();
        Ok(buf)
    }

    /// Write a value to `<prefix>.<key>` in the repo-local git config.
    ///
    /// Note: while the value is stored verbatim, [`Repo::get_config`]
    /// currently **trims leading/trailing whitespace on read**, so stored
    /// values (in particular the password) effectively cannot contain
    /// surrounding whitespace. The interactive prompt trims its input for
    /// the same reason.
    pub fn set_config(&self, key: &str, value: &str) -> Result<()> {
        let temp = String::from(GIT_CONFIG_PREFIX) + key;
        self.run(&["config", "--local", &temp, value])
    }

    /// Read `<prefix>.<key>` from the repo-local git config.
    ///
    /// Wrapped in [`Zeroizing`]: the one remaining caller reads the password
    /// left behind by older versions ([`Repo::scrub_legacy_key`]), so the
    /// value must not linger in memory after the read.
    pub fn get_config(&self, key: &str) -> Result<Zeroizing<String>> {
        let temp = String::from(GIT_CONFIG_PREFIX) + key;
        let raw = Zeroizing::new(self.run_with_output(&["config", "--get", &temp])?);
        Ok(Zeroizing::new(raw.trim().to_string()))
    }
}

/// What kind of index entry a staged path refers to.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum StagedKind {
    /// A regular file blob (mode 100644 / 100755) — the only thing git-se
    /// encrypts, and therefore the only thing it can check.
    Regular,
    /// An unmerged path (conflict). Its content lives at stages 1/2/3, so
    /// `git show :<path>` cannot read it.
    Unmerged,
    /// A symlink (120000) or gitlink/submodule (160000).
    Other,
}

/// One entry of `git diff --cached --raw -z` output.
#[derive(Debug)]
struct StagedEntry {
    kind: StagedKind,
    path: PathBuf,
}

/// Parse `git diff --cached --raw -z` output.
///
/// Each record is `:<srcmode> <dstmode> <srcsha> <dstsha> <status>\0<path>\0`,
/// except renames and copies, which carry `\0<src>\0<dst>\0` — for those the
/// **destination** is what the commit will contain.
fn parse_raw_z(raw: &[u8]) -> Vec<StagedEntry> {
    let mut out = Vec::new();
    let mut fields = raw.split(|&b| b == 0).filter(|s| !s.is_empty());

    while let Some(meta) = fields.next() {
        // Anything not starting with ':' means the stream got out of sync;
        // skipping a path is safer than pairing it with the wrong metadata.
        let Some(meta) = meta.strip_prefix(b":") else {
            continue;
        };
        let meta = String::from_utf8_lossy(meta);
        let mut parts = meta.split(' ');
        let (_src_mode, dst_mode, _src_sha, _dst_sha, status) = (
            parts.next(),
            parts.next().unwrap_or_default(),
            parts.next(),
            parts.next(),
            parts.next().unwrap_or_default(),
        );

        let is_rename_or_copy = status.starts_with('R') || status.starts_with('C');
        let Some(first) = fields.next() else { break };
        let path = if is_rename_or_copy {
            let Some(dst) = fields.next() else { break };
            dst
        } else {
            first
        };

        let kind = if status.starts_with('U') {
            StagedKind::Unmerged
        } else if matches!(dst_mode, "100644" | "100755") {
            StagedKind::Regular
        } else {
            StagedKind::Other
        };

        out.push(StagedEntry {
            kind,
            path: git_z_path(path),
        });
    }
    out
}

/// Git environment variables that select a *different* repository.
///
/// Left in place, the ambient environment silently redirects every git call:
/// `check --staged` would inspect a foreign index (letting this repo's staged
/// plaintext through) and `install` would drop the hook into a foreign repo.
/// Repository selection must come from the resolved `--repo`, nothing else.
///
/// `GIT_INDEX_FILE` is deliberately *not* listed — see [`Repo::git_command`].
const GIT_REPO_ENV_VARS: &[&str] = &[
    "GIT_DIR",
    "GIT_WORK_TREE",
    "GIT_COMMON_DIR",
    "GIT_NAMESPACE",
    "GIT_OBJECT_DIRECTORY",
    "GIT_ALTERNATE_OBJECT_DIRECTORIES",
    "GIT_CEILING_DIRECTORIES",
    "GIT_DISCOVERY_ACROSS_FILESYSTEM",
    "GIT_PREFIX",
];

/// Run `git rev-parse <flag>` in `repo_path` and return the trimmed stdout.
///
/// Uses the same sanitized environment as every other git call, so the
/// repository being described cannot be swapped out from under us.
fn rev_parse_flag(repo_path: &Path, flag: &str) -> Option<String> {
    let mut cmd = std::process::Command::new("git");
    cmd.current_dir(repo_path)
        .args(["rev-parse", flag])
        .env_remove(crate::utils::PASSWORD_ENV_VAR);
    for var in GIT_REPO_ENV_VARS {
        cmd.env_remove(var);
    }
    let output = cmd.output().ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = String::from_utf8(output.stdout).ok()?;
    let trimmed = stdout.trim();
    if trimmed.is_empty() {
        return None;
    }
    Some(trimmed.to_owned())
}

/// [`rev_parse_flag`], interpreted as a canonical absolute path.
fn rev_parse_path(repo_path: &Path, flag: &str) -> Option<PathBuf> {
    let trimmed = rev_parse_flag(repo_path, flag)?;
    // `--git-common-dir` may print a path relative to the current dir;
    // absolutize against the repo path (a no-op when already absolute).
    let path = Path::new(&trimmed).absolutize_from(repo_path).into_owned();
    // Canonicalize so the result is in real-path form regardless of
    // whether git printed a relative or absolute path — git resolves
    // symlinks (e.g. macOS /var -> /private/var) but the repo path may
    // still contain them.
    Some(path.canonicalize().unwrap_or(path))
}

/// Resolve the per-worktree git dir and the common git dir for `repo_path`
/// via `git rev-parse`.
///
/// Both fall back gracefully when `git` is unavailable or the directory is
/// not a git repository: `git_dir` falls back to `<repo>/.git` (the
/// historical behavior) and `git_common_dir` falls back to `git_dir`.
fn resolve_git_dirs(repo_path: &Path) -> (PathBuf, PathBuf) {
    let git_dir =
        rev_parse_path(repo_path, "--absolute-git-dir").unwrap_or_else(|| repo_path.join(".git"));
    let git_common_dir =
        rev_parse_path(repo_path, "--git-common-dir").unwrap_or_else(|| git_dir.clone());
    debug!(
        "git dir: {}, common git dir: {}",
        git_dir.display(),
        git_common_dir.display()
    );
    (git_dir, git_common_dir)
}

#[cfg(test)]
mod tests {
    use std::process::Command;

    use path_absolutize::Absolutize;
    use tempfile::TempDir;

    use super::*;

    #[test]
    fn test_repo_open() -> Result<()> {
        let repo = Repo::open(Path::new(".").absolutize()?)?;
        assert_eq!(repo.path().file_name().unwrap(), "git-simple-encrypt");
        let repo = Repo::open(Path::new("./.git").absolutize()?)?;
        assert_eq!(repo.path().file_name().unwrap(), "git-simple-encrypt");
        Ok(())
    }

    fn init_temp_repo() -> TempDir {
        let dir = TempDir::new().unwrap();
        // `git init` so that .git/ exists for hook installation & config.
        Command::new("git")
            .args(["init"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        dir
    }

    #[test]
    fn test_set_get_config_roundtrip() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        repo.set_config("key", "hunter2")?;
        let read_back = repo.get_config("key")?;
        assert_eq!(read_back.as_str(), "hunter2");
        Ok(())
    }

    #[test]
    fn test_scrub_legacy_key() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        // Simulate a password stored by an older version. (The automatic
        // scrub on `Repo::open` is disabled under cfg(test), so call it
        // explicitly here.)
        repo.set_config("key", "hunter2")?;
        assert!(repo.get_config("key").is_ok());

        repo.scrub_legacy_key();
        assert!(repo.get_config("key").is_err());

        // Idempotent: scrubbing again is a no-op.
        repo.scrub_legacy_key();
        Ok(())
    }

    #[test]
    fn test_install_hook_creates_file() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        repo.install_hook()?;
        let hook = repo_path.join(".git").join("hooks").join("pre-commit");
        assert!(hook.exists());
        let content = std::fs::read(&hook)?;
        assert!(
            content.starts_with(b"#!/bin/sh"),
            "hook should be a shell script"
        );

        // Second install must fail (idempotency guard).
        let second = repo.install_hook();
        assert!(matches!(second, Err(Error::HookExists(_))));
        Ok(())
    }

    #[test]
    fn test_worktree_git_dir_resolution() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();

        // A commit is required before `git worktree add`.
        std::fs::write(repo_path.join("f.txt"), "x")?;
        Command::new("git")
            .args(["add", "f.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        let commit = Command::new("git")
            .args([
                "-c",
                "user.email=t@example.com",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "init",
            ])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(commit.status.success(), "commit failed: {commit:?}");

        let wt_parent = TempDir::new().unwrap();
        let wt_path = wt_parent.path().join("wt");
        let out = Command::new("git")
            .args(["worktree", "add", wt_path.to_str().unwrap()])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(out.status.success(), "worktree add failed: {out:?}");

        let wt_repo = Repo::open(&wt_path)?;
        assert!(
            wt_repo.git_dir().ends_with(".git/worktrees/wt"),
            "unexpected worktree git dir: {}",
            wt_repo.git_dir().display()
        );
        // git reports real paths (symlinks resolved, e.g. macOS
        // /var -> /private/var), so compare canonicalized forms.
        assert_eq!(
            wt_repo.git_common_dir,
            repo_path.join(".git").canonicalize()?
        );

        // The hook must land in the *common* dir so it fires for all worktrees.
        wt_repo.install_hook()?;
        assert!(repo_path.join(".git/hooks/pre-commit").exists());
        Ok(())
    }

    /// Opening a repo through a symlinked path must still yield canonical
    /// git dirs (macOS: /var -> /private/var; this reproduces it on Linux).
    #[cfg(unix)]
    #[test]
    fn test_repo_open_via_symlinked_path() -> Result<()> {
        let dir = init_temp_repo();
        let link_parent = TempDir::new().unwrap();
        let link = link_parent.path().join("repo-link");
        std::os::unix::fs::symlink(dir.path(), &link)?;

        let repo = Repo::open(&link)?;
        let expected = dir.path().join(".git").canonicalize()?;
        assert_eq!(repo.git_dir(), &expected);
        assert_eq!(repo.git_common_dir, expected);
        Ok(())
    }

    #[test]
    fn test_check_reports_unencrypted() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let mut repo = Repo::open(&repo_path)?;

        // Add a plaintext file to the crypt list.
        std::fs::write(repo_path.join("plain.txt"), b"hello")?;
        repo.conf.add_one_path_to_crypt_list("plain.txt")?;

        // check should return FilesNotEncrypted.
        let result = repo.check(&[], false);
        assert!(matches!(result, Err(Error::FilesNotEncrypted(1, 1))));

        // A bare header is NOT enough (M-01): without a complete chunk the
        // file cannot be real ciphertext, so the check must keep failing.
        let header = crate::crypt::FileHeader::new(false, [0x11; 16], [0x22; 16]);
        std::fs::write(repo_path.join("plain.txt"), header.as_bytes()).unwrap();
        let result = repo.check(&[], false);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "a header with no chunk must not pass as encrypted: {result:?}"
        );

        // A header followed by a complete minimal chunk does pass the format
        // check (it cannot be authenticated without the password).
        std::fs::write(repo_path.join("plain.txt"), fake_encrypted_blob(&header))?;
        assert!(repo.check(&[], false).is_ok());
        Ok(())
    }

    /// A byte string that satisfies the format check: a valid header plus one
    /// complete (garbage) chunk. Only the *format* is valid — there is no
    /// password behind it, which is exactly what the format check can't tell.
    #[cfg(test)]
    fn fake_encrypted_blob(header: &crate::crypt::FileHeader) -> Vec<u8> {
        let mut blob = header.as_bytes().to_vec();
        blob.extend_from_slice(&[0u8; crate::crypt::NONCE_LEN + 16]);
        blob
    }

    /// Regression (H-01): `check --staged` must inspect the staged blob, not
    /// the working-tree file. Stage plaintext, then encrypt the working tree:
    /// the check must still fail because the index holds plaintext.
    #[test]
    fn test_check_staged_reads_index_blob() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let mut repo = Repo::open(&repo_path)?;

        std::fs::write(repo_path.join("s.txt"), b"PLAINTEXT")?;
        repo.conf.add_one_path_to_crypt_list("s.txt")?;

        // Stage the plaintext version.
        Command::new("git")
            .args(["add", "s.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();

        // Now the working tree gets an encrypted-looking file.
        let header = crate::crypt::FileHeader::new(false, [0x11; 16], [0x22; 16]);
        std::fs::write(repo_path.join("s.txt"), fake_encrypted_blob(&header))?;

        // The staged blob is still plaintext — check must fail even though
        // the working tree looks encrypted.
        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "staged plaintext must fail even with encrypted worktree: {result:?}"
        );

        // Stage the encrypted version too → now the index is encrypted.
        Command::new("git")
            .args(["add", "s.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(repo.check(&[], true).is_ok());
        Ok(())
    }

    /// Regression (H-01): a file staged as plaintext and then deleted from
    /// the working tree must still be caught (the staged blob is what gets
    /// committed).
    #[test]
    fn test_check_staged_deleted_worktree() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let mut repo = Repo::open(&repo_path)?;

        std::fs::write(repo_path.join("s.txt"), b"PLAINTEXT")?;
        repo.conf.add_one_path_to_crypt_list("s.txt")?;
        Command::new("git")
            .args(["add", "s.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();

        // Delete the working-tree file after staging plaintext.
        std::fs::remove_file(repo_path.join("s.txt"))?;

        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "deleted-from-worktree staged plaintext must fail: {result:?}"
        );
        Ok(())
    }

    /// Write a config file with the given crypt list and return the repo.
    fn repo_with_crypt_list(repo_path: &Path, entries: &[&str]) -> Result<Repo> {
        let list = entries
            .iter()
            .map(|e| format!("{e:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        std::fs::write(
            repo_path.join(CONFIG_FILE_NAME),
            format!("use_zstd = true\nzstd_level = 15\ncrypt_list = [{list}]\n"),
        )?;
        Repo::open(repo_path)
    }

    fn git(args: &[&str], pwd: &Path) {
        let out = Command::new("git")
            .args(args)
            .current_dir(pwd)
            .output()
            .unwrap();
        assert!(out.status.success(), "git {args:?} failed: {out:?}");
    }

    /// Regression (H-01): a crypt-list *directory* that no longer exists in
    /// the working tree must still cover its staged blobs. The old
    /// `repo.join(entry).is_dir()` test silently unlisted every one of them.
    #[test]
    fn test_check_staged_directory_deleted_from_worktree() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        std::fs::create_dir(repo_path.join("secrets"))?;
        std::fs::write(repo_path.join("secrets/a.txt"), b"PLAINTEXT")?;
        let repo = repo_with_crypt_list(&repo_path, &["secrets"])?;

        git(&["add", "-A"], &repo_path);
        std::fs::remove_dir_all(repo_path.join("secrets"))?;

        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "staged blobs under a deleted crypt-list dir must be checked: {result:?}"
        );
        Ok(())
    }

    /// Regression (H-01): a committed symlink replaced by a plaintext regular
    /// file is a typechange (`T`), which the old `--diff-filter=ACMR` dropped.
    #[cfg(unix)]
    #[test]
    fn test_check_staged_typechange() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        // A repo-relative (and deliberately dangling) target: git stores the
        // link text as the blob, so what it points at is irrelevant, and this
        // avoids assuming any particular system file exists.
        std::os::unix::fs::symlink("link-target", repo_path.join("s.txt"))?;
        let repo = repo_with_crypt_list(&repo_path, &["s.txt"])?;

        git(&["add", "-A"], &repo_path);
        git(
            &[
                "-c",
                "user.email=t@e.com",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "init",
            ],
            &repo_path,
        );

        // symlink -> regular plaintext file
        std::fs::remove_file(repo_path.join("s.txt"))?;
        std::fs::write(repo_path.join("s.txt"), b"PLAINTEXT_SECRET")?;
        git(&["add", "s.txt"], &repo_path);

        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "a symlink->regular typechange must be checked: {result:?}"
        );
        Ok(())
    }

    /// Regression (H-01): the policy must come from the *index* copy of the
    /// config. Emptying `crypt_list` in the working tree without staging it
    /// used to disable the check for a commit that still demanded encryption.
    #[test]
    fn test_check_staged_uses_index_config() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        std::fs::write(repo_path.join("secret.txt"), b"PLAINTEXT_SECRET")?;
        repo_with_crypt_list(&repo_path, &["secret.txt"])?;
        git(&["add", "-A"], &repo_path);

        // Working tree now says "encrypt nothing" — but that is NOT staged.
        let repo = repo_with_crypt_list(&repo_path, &[])?;
        assert!(repo.conf.crypt_list.is_empty());

        let result = repo.check(&[], true);
        assert!(
            matches!(result, Err(Error::FilesNotEncrypted(1, 1))),
            "the staged config must decide the policy: {result:?}"
        );
        Ok(())
    }

    /// Regression: with the whole-repo entry `.`, the config file itself must
    /// not be demanded encrypted — it is excluded from encryption, so the
    /// check would have been permanently unsatisfiable.
    #[test]
    fn test_check_staged_dot_entry_excludes_config() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = repo_with_crypt_list(&repo_path, &["."])?;
        git(&["add", CONFIG_FILE_NAME], &repo_path);

        assert!(
            repo.check(&[], true).is_ok(),
            "the git-se config must never be checked for encryption"
        );
        Ok(())
    }

    /// Regression (H-02): a path inside the git dir is not a repository root.
    /// Accepting `<repo>/.git/refs` used to encrypt `refs/heads/*`, which
    /// destroys the repository.
    #[test]
    fn test_repo_open_rejects_paths_inside_git_dir() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();

        for inside in [".git/refs", ".git/objects", ".git/hooks"] {
            let path = repo_path.join(inside);
            std::fs::create_dir_all(&path)?;
            assert!(
                matches!(Repo::open(&path), Err(Error::PathInsideGitDir(_))),
                "{inside} must be rejected as a repo root"
            );
        }
        Ok(())
    }

    /// Regression (H-02): `.GIT` (an alias symlink, or a case-insensitive
    /// filesystem) must resolve to the worktree root, never to the git dir.
    #[cfg(unix)]
    #[test]
    fn test_repo_open_git_alias_resolves_to_worktree() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let alias = repo_path.join(".GIT");

        // On a case-insensitive filesystem (the macOS default) `.GIT` already
        // *is* `.git`, so creating the alias would fail with EEXIST — that
        // platform reaches the case under test natively. Elsewhere a symlink
        // reproduces the same shape.
        if !alias.exists() {
            std::os::unix::fs::symlink(".git", &alias)?;
        }

        let repo = Repo::open(&alias)?;
        assert_eq!(
            repo.path().canonicalize()?,
            repo_path.canonicalize()?,
            "`.GIT` must open the worktree, not the git dir"
        );
        Ok(())
    }
}
