use std::{
    collections::HashSet,
    path::{Path, PathBuf},
};

use config_file2::LoadConfigFile;
use log::{debug, info, warn};
use parking_lot::Mutex;
use path_absolutize::Absolutize;
use rayon::prelude::*;

use crate::{
    config::{CONFIG_FILE_NAME, Config},
    error::{Error, Result},
    utils::{
        Progress, git_z_path, is_file_encrypted, prompt_password, resolve_target_files,
        style::Colorize,
    },
};

pub const GIT_CONFIG_PREFIX: &str =
    const_str::replace!(concat!(env!("CARGO_CRATE_NAME"), "."), "_", "-");

/// The pre-commit hook content that runs `git-se check --staged` before every
/// commit, so only files part of the current commit are checked.
const PRE_COMMIT_HOOK: &[u8] = br#"#!/bin/sh
# Auto-generated by git-se install
git-se check --staged
if [ $? -ne 0 ]; then
    echo "Please run 'git-se e' to encrypt them before committing."
    exit 1
fi
"#;

#[derive(Debug, Clone, Default)]
pub struct Repo {
    /// The absolute path of the opened repo.
    pub path: PathBuf,
    /// The resolved per-worktree git dir (`git rev-parse --absolute-git-dir`,
    /// canonicalized).
    ///
    /// Equals `<path>/.git` for a normal repository, but differs for linked
    /// worktrees (`<main>/.git/worktrees/<name>`) and submodules
    /// (`<superproject>/.git/modules/<name>`). Falls back to `<path>/.git`
    /// when `git` is unavailable or the directory is not a git repository.
    pub git_dir: PathBuf,
    /// The resolved common git dir (`git rev-parse --git-common-dir`,
    /// canonicalized), where hooks and shared config live. Equals
    /// [`Repo::git_dir`] unless this is a linked worktree.
    pub git_common_dir: PathBuf,
    pub conf: Config,
}

impl Repo {
    /// Open a repo. The `path` argument must be an absolute path.
    pub fn open(path: impl AsRef<Path>) -> Result<Self> {
        debug_assert!(path.as_ref().is_absolute(), "given path must be absolute");
        let mut repo_path = path.as_ref().to_path_buf();
        if !repo_path.exists() {
            return Err(Error::RepoNotFound(repo_path));
        }
        if !repo_path.is_dir() {
            return Err(Error::NotADirectory(repo_path));
        }
        if repo_path
            .file_name()
            .ok_or_else(|| Error::Other("Filename not found".to_string()))?
            == ".git"
        {
            repo_path.pop();
        }
        info!("Open repo: {}", repo_path.display());
        let (git_dir, git_common_dir) = resolve_git_dirs(&repo_path);
        let config_file_path = repo_path.join(CONFIG_FILE_NAME);
        if !config_file_path.exists() {
            warn!(
                "Config file not found: `{}`, using default config instead...",
                config_file_path.display()
            );
        }
        let conf = Config::load_or_default(&config_file_path)
            .map_err(|e| Error::Config(e.to_string()))?
            .with_repo_path(&repo_path);
        let repo = Self {
            path: repo_path,
            git_dir,
            git_common_dir,
            conf,
        };
        // Scrub passwords stored by older versions. Skipped in unit tests so
        // that running the test suite cannot touch a real repo's config.
        #[cfg(not(test))]
        repo.scrub_legacy_key();
        Ok(repo)
    }

    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// The per-worktree git dir (see [`Repo::git_dir`]).
    #[must_use]
    pub fn git_dir(&self) -> &Path {
        &self.git_dir
    }

    pub fn to_absolute_path(&self, path: impl AsRef<Path>) -> PathBuf {
        self.path.join(path.as_ref())
    }

    /// Change the master password: decrypt every listed file with the old
    /// password, then re-encrypt everything with the new one.
    ///
    /// The old password is taken from `GIT_SE_PASSWORD` when set, otherwise
    /// prompted; the new password is always prompted (twice, echo disabled).
    /// Nothing is persisted anywhere — the password only lives in memory for
    /// the duration of the operation.
    pub fn change_password_interactive(&self) -> Result<()> {
        use crate::crypt::{decrypt_repo, encrypt_repo};

        let target_files =
            crate::utils::resolve_target_files(&[], &self.conf.crypt_list, self.path())?;
        let encrypted_count = target_files
            .iter()
            .filter(|f| crate::utils::is_file_encrypted(f).unwrap_or(false))
            .count();
        if encrypted_count == 0 {
            println!(
                "No encrypted files in the crypt list; nothing to re-encrypt. \
                 The password is set implicitly at the next `git-se e`."
            );
            return Ok(());
        }

        let old_key = crate::utils::get_password("Please input your OLD key: ")?;
        // Fast sanity check before starting: with no encrypted working-tree
        // files we cannot pre-check, but at this point we know there are.
        decrypt_repo(self, &[], old_key.as_bytes())?;

        let new_key = prompt_password("Please input your NEW key: ")?;
        let confirm = prompt_password("Please confirm your NEW key: ")?;
        if new_key.as_str() != confirm.as_str() {
            return Err(Error::PasswordMismatch);
        }

        // HEAD still holds files encrypted with the OLD password, so the
        // consistency check must be bypassed — this IS the password change.
        encrypt_repo(self, &[], new_key.as_bytes(), true)?;
        info!("Master key changed; all listed files were re-encrypted.");
        Ok(())
    }

    /// One-time migration: versions that stored the password in the repo-local
    /// git config get it scrubbed. Best-effort; only logs on failure.
    pub fn scrub_legacy_key(&self) {
        let legacy_key = format!("{GIT_CONFIG_PREFIX}key");
        if self.get_config("key").is_err() {
            return;
        }
        if self.run(&["config", "--unset", &legacy_key]).is_ok() {
            warn!(
                "Removed the password stored in .git/config by an older git-se version; \
                 passwords are no longer persisted."
            );
        } else {
            warn!(
                "A password from an older git-se version is still stored in .git/config and \
                 could not be removed automatically; please run \
                 `git config --local --unset {legacy_key}`."
            );
        }
    }

    /// Check if all files in the crypt list (or given paths) are encrypted.
    ///
    /// When `staged` is true, only files staged for the current commit are
    /// checked, by intersecting staged files against the crypt list. This is
    /// used by the pre-commit hook to avoid checking the entire repo.
    ///
    /// Returns `Ok(())` if all files are encrypted, or an error summarizing
    /// which files are not encrypted. The process exits with a non-zero code
    /// when files are not encrypted, suitable for CI usage.
    pub fn check(&self, paths: &[PathBuf], staged: bool) -> Result<()> {
        let target_files = if staged {
            // `-z` makes git print filenames verbatim, NUL-separated and
            // without C-style quoting. Line-based parsing (plus trimming) of
            // the default output would mangle non-ASCII / special-character
            // filenames and silently skip them — a plaintext-leak vector.
            let staged_output = self.run_with_output_bytes(&[
                "diff",
                "--cached",
                "--name-only",
                "-z",
                "--diff-filter=ACMR",
            ])?;
            let crypt_files: HashSet<PathBuf> =
                resolve_target_files(&[], &self.conf.crypt_list, self.path())?
                    .into_iter()
                    .collect();

            staged_output
                .split(|&b| b == 0)
                .filter(|name| !name.is_empty())
                .map(|name| self.path.join(git_z_path(name)))
                .filter(|p| p.exists())
                .filter(|f| crypt_files.contains(f))
                .collect()
        } else {
            resolve_target_files(paths, &self.conf.crypt_list, self.path())?
        };

        if staged && target_files.is_empty() {
            println!("No staged files need encryption check.");
            return Ok(());
        }
        if target_files.is_empty() {
            return Err(Error::NoFile("check"));
        }

        println!(
            "\n{} {} {}",
            "Checking encryption status".bold(),
            format!("({} files)", target_files.len()).cyan(),
            ":".dimmed()
        );

        let pb = Progress::new(target_files.len(), "Check");
        let not_encrypted: Mutex<Vec<PathBuf>> = Mutex::new(Vec::new());

        target_files.par_iter().try_for_each(|f| -> Result<()> {
            if !is_file_encrypted(f)? {
                let mut list = not_encrypted.lock();
                let relative = pathdiff::diff_paths(f, &self.path).unwrap_or_else(|| f.clone());
                list.push(relative);
            }
            pb.inc(1);
            Ok(())
        })?;

        pb.finish_and_clear();

        let not_encrypted = not_encrypted.into_inner();
        let total = target_files.len();
        let encrypted_count = total - not_encrypted.len();

        if not_encrypted.is_empty() {
            println!(
                "\n{}: All {} files are encrypted.",
                "Check complete".bold(),
                total.to_string().green(),
            );
            Ok(())
        } else {
            println!(
                "\n{} files are {}:",
                not_encrypted.len().to_string().yellow(),
                "NOT encrypted".yellow()
            );
            for f in &not_encrypted {
                println!("  - {}", f.display());
            }

            println!(
                "\n{}: {}/{} files encrypted",
                "Check complete".bold(),
                encrypted_count.to_string().green(),
                total,
            );

            Err(Error::FilesNotEncrypted(not_encrypted.len(), total))
        }
    }

    /// Install a pre-commit hook that runs `git-se check` before each commit.
    ///
    /// Creates `<git-common-dir>/hooks/pre-commit` with the check script.
    /// The common dir (not the per-worktree git dir) is used so the hook also
    /// works for linked worktrees. Fails if a hook already exists and is not
    /// managed by git-se.
    pub fn install_hook(&self) -> Result<()> {
        let hooks_dir = self.git_common_dir.join("hooks");
        std::fs::create_dir_all(&hooks_dir)?;

        let hook_path = hooks_dir.join("pre-commit");

        // Check if hook already exists
        if hook_path.exists() {
            return Err(Error::HookExists(hook_path));
        }

        std::fs::write(&hook_path, PRE_COMMIT_HOOK)?;

        // Set executable permission on unix. Windows users need Git for Windows
        // (msys-based) which executes the sh hook regardless of the executable
        // bit; a normal `write` is sufficient there.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&hook_path)?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&hook_path, perms)?;
        }

        println!(
            "{} pre-commit hook at {}",
            "Installed".green().bold(),
            hook_path.display()
        );
        Ok(())
    }

    /// Run a `git` command in the repo, discarding its stdout/stderr.
    pub fn run(&self, args: &[&str]) -> Result<()> {
        let output = std::process::Command::new("git")
            .current_dir(&self.path)
            .args(args)
            .output()?;
        if !output.status.success() {
            return Err(Error::Git(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }
        Ok(())
    }

    /// Run a `git` command and return its stdout as a `String`.
    pub fn run_with_output(&self, args: &[&str]) -> Result<String> {
        String::from_utf8(self.run_with_output_bytes(args)?)
            .map_err(|e| Error::Other(format!("git output not UTF-8: {e}")))
    }

    /// Run a `git` command and return its raw stdout bytes.
    ///
    /// Needed for `-z` output, which is NUL-separated and may contain
    /// non-UTF-8 filenames.
    pub fn run_with_output_bytes(&self, args: &[&str]) -> Result<Vec<u8>> {
        let mut cmd = std::process::Command::new("git");

        // Force English output in tests so we can match on stderr reliably.
        if cfg!(test) {
            cmd.env("LC_ALL", "C.UTF-8").env("LANGUAGE", "C.UTF-8");
        }

        let output = cmd.current_dir(&self.path).args(args).output()?;
        if !output.status.success() {
            return Err(Error::Git(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }
        Ok(output.stdout)
    }

    /// Run a `git` command, capturing at most `cap` bytes of stdout.
    ///
    /// The child is killed once `cap` bytes have been read, so this stays
    /// cheap even for huge blobs (e.g. `git show HEAD:large.bin` during the
    /// password pre-check). Because of the early kill, the exit status is
    /// meaningless and therefore ignored: callers must treat an empty result
    /// as "no usable output".
    pub(crate) fn run_with_output_bytes_capped(
        &self,
        args: &[&str],
        cap: usize,
    ) -> Result<Vec<u8>> {
        use std::io::Read as _;
        let mut child = std::process::Command::new("git")
            .current_dir(&self.path)
            .args(args)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::null())
            .spawn()?;
        let mut buf = Vec::new();
        if let Some(stdout) = child.stdout.take() {
            stdout.take(cap as u64).read_to_end(&mut buf)?;
        }
        let _ = child.kill(); // no-op when git already exited (blob smaller than cap)
        let _ = child.wait();
        Ok(buf)
    }

    /// Write a value to `<prefix>.<key>` in the repo-local git config.
    ///
    /// Note: while the value is stored verbatim, [`Repo::get_config`]
    /// currently **trims leading/trailing whitespace on read**, so stored
    /// values (in particular the password) effectively cannot contain
    /// surrounding whitespace. The interactive prompt trims its input for
    /// the same reason.
    pub fn set_config(&self, key: &str, value: &str) -> Result<()> {
        let temp = String::from(GIT_CONFIG_PREFIX) + key;
        self.run(&["config", "--local", &temp, value])
    }

    /// Read `<prefix>.<key>` from the repo-local git config.
    pub fn get_config(&self, key: &str) -> Result<String> {
        let temp = String::from(GIT_CONFIG_PREFIX) + key;
        self.run_with_output(&["config", "--get", &temp])
            .map(|x| x.trim().to_string())
    }
}

/// Resolve the per-worktree git dir and the common git dir for `repo_path`
/// via `git rev-parse`.
///
/// Both fall back gracefully when `git` is unavailable or the directory is
/// not a git repository: `git_dir` falls back to `<repo>/.git` (the
/// historical behavior) and `git_common_dir` falls back to `git_dir`.
fn resolve_git_dirs(repo_path: &Path) -> (PathBuf, PathBuf) {
    fn rev_parse(repo_path: &Path, flag: &str) -> Option<PathBuf> {
        let output = std::process::Command::new("git")
            .current_dir(repo_path)
            .args(["rev-parse", flag])
            .output()
            .ok()?;
        if !output.status.success() {
            return None;
        }
        let stdout = String::from_utf8(output.stdout).ok()?;
        let trimmed = stdout.trim();
        if trimmed.is_empty() {
            return None;
        }
        // `--git-common-dir` may print a path relative to the current dir;
        // absolutize against the repo path (a no-op when already absolute).
        let path = Path::new(trimmed).absolutize_from(repo_path).into_owned();
        // Canonicalize so the result is in real-path form regardless of
        // whether git printed a relative or absolute path — git resolves
        // symlinks (e.g. macOS /var -> /private/var) but the repo path may
        // still contain them.
        Some(path.canonicalize().unwrap_or(path))
    }

    let git_dir =
        rev_parse(repo_path, "--absolute-git-dir").unwrap_or_else(|| repo_path.join(".git"));
    let git_common_dir =
        rev_parse(repo_path, "--git-common-dir").unwrap_or_else(|| git_dir.clone());
    debug!(
        "git dir: {}, common git dir: {}",
        git_dir.display(),
        git_common_dir.display()
    );
    (git_dir, git_common_dir)
}

#[cfg(test)]
mod tests {
    use std::process::Command;

    use path_absolutize::Absolutize;
    use tempfile::TempDir;

    use super::*;
    use crate::crypt::HEADER_LEN;

    #[test]
    fn test_repo_open() -> Result<()> {
        let repo = Repo::open(Path::new(".").absolutize()?)?;
        assert_eq!(repo.path().file_name().unwrap(), "git-simple-encrypt");
        let repo = Repo::open(Path::new("./.git").absolutize()?)?;
        assert_eq!(repo.path().file_name().unwrap(), "git-simple-encrypt");
        Ok(())
    }

    fn init_temp_repo() -> TempDir {
        let dir = TempDir::new().unwrap();
        // `git init` so that .git/ exists for hook installation & config.
        Command::new("git")
            .args(["init"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        dir
    }

    #[test]
    fn test_set_get_config_roundtrip() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        repo.set_config("key", "hunter2")?;
        let read_back = repo.get_config("key")?;
        assert_eq!(read_back, "hunter2");
        Ok(())
    }

    #[test]
    fn test_scrub_legacy_key() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        // Simulate a password stored by an older version. (The automatic
        // scrub on `Repo::open` is disabled under cfg(test), so call it
        // explicitly here.)
        repo.set_config("key", "hunter2")?;
        assert!(repo.get_config("key").is_ok());

        repo.scrub_legacy_key();
        assert!(repo.get_config("key").is_err());

        // Idempotent: scrubbing again is a no-op.
        repo.scrub_legacy_key();
        Ok(())
    }

    #[test]
    fn test_install_hook_creates_file() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        repo.install_hook()?;
        let hook = repo_path.join(".git").join("hooks").join("pre-commit");
        assert!(hook.exists());
        let content = std::fs::read(&hook)?;
        assert!(
            content.starts_with(b"#!/bin/sh"),
            "hook should be a shell script"
        );

        // Second install must fail (idempotency guard).
        let second = repo.install_hook();
        assert!(matches!(second, Err(Error::HookExists(_))));
        Ok(())
    }

    #[test]
    fn test_worktree_git_dir_resolution() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();

        // A commit is required before `git worktree add`.
        std::fs::write(repo_path.join("f.txt"), "x")?;
        Command::new("git")
            .args(["add", "f.txt"])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        let commit = Command::new("git")
            .args([
                "-c",
                "user.email=t@example.com",
                "-c",
                "user.name=t",
                "commit",
                "-qm",
                "init",
            ])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(commit.status.success(), "commit failed: {commit:?}");

        let wt_parent = TempDir::new().unwrap();
        let wt_path = wt_parent.path().join("wt");
        let out = Command::new("git")
            .args(["worktree", "add", wt_path.to_str().unwrap()])
            .current_dir(&repo_path)
            .output()
            .unwrap();
        assert!(out.status.success(), "worktree add failed: {out:?}");

        let wt_repo = Repo::open(&wt_path)?;
        assert!(
            wt_repo.git_dir().ends_with(".git/worktrees/wt"),
            "unexpected worktree git dir: {}",
            wt_repo.git_dir().display()
        );
        // git reports real paths (symlinks resolved, e.g. macOS
        // /var -> /private/var), so compare canonicalized forms.
        assert_eq!(
            wt_repo.git_common_dir,
            repo_path.join(".git").canonicalize()?
        );

        // The hook must land in the *common* dir so it fires for all worktrees.
        wt_repo.install_hook()?;
        assert!(repo_path.join(".git/hooks/pre-commit").exists());
        Ok(())
    }

    /// Opening a repo through a symlinked path must still yield canonical
    /// git dirs (macOS: /var -> /private/var; this reproduces it on Linux).
    #[cfg(unix)]
    #[test]
    fn test_repo_open_via_symlinked_path() -> Result<()> {
        let dir = init_temp_repo();
        let link_parent = TempDir::new().unwrap();
        let link = link_parent.path().join("repo-link");
        std::os::unix::fs::symlink(dir.path(), &link)?;

        let repo = Repo::open(&link)?;
        let expected = dir.path().join(".git").canonicalize()?;
        assert_eq!(repo.git_dir(), &expected);
        assert_eq!(repo.git_common_dir, expected);
        Ok(())
    }

    #[test]
    fn test_check_reports_unencrypted() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let mut repo = Repo::open(&repo_path)?;

        // Add a plaintext file to the crypt list.
        std::fs::write(repo_path.join("plain.txt"), b"hello")?;
        repo.conf.add_one_path_to_crypt_list("plain.txt")?;

        // check should return FilesNotEncrypted.
        let result = repo.check(&[], false);
        assert!(matches!(result, Err(Error::FilesNotEncrypted(1, 1))));

        // Encrypt the file (cheap path: just give it a valid 64-byte GITSE header so
        // is_file_encrypted returns true), then check passes.
        let mut fake_header = vec![0u8; HEADER_LEN];
        fake_header[..5].copy_from_slice(b"GITSE");
        fake_header[5] = 3; // version
        std::fs::write(repo_path.join("plain.txt"), fake_header).unwrap();
        let result = repo.check(&[], false);
        assert!(result.is_ok());
        Ok(())
    }
}
